"""Source identity and declared scope for AFrame; no geometry or strength rules.

REGISTRY is the single authored catalogue. assembly_catalog.json is an audit
snapshot generated by this module, never a runtime dependency. An accepted
identity is not approval of an assembly, a calculation or a manufacturer node.
"""
import copy
import json

REGISTRY_REVISION = "2026-09-30.atr-1"
SUPPORTED_SCHEMES = ("vertical", "ortho", "interfloor")
SUPPORTED_CLADDINGS = ("porcelain", "composite", "concrete", "clinker")

REGISTRY = {
    "schema": "aframe_assembly_registry/1",
    "revision": REGISTRY_REVISION,
    "authority": "source_and_implementation_scope_registry",
    "design_limits": False,
    "manufacturer_compliance": "not_asserted",
    "accepted_code_schemes": list(SUPPORTED_SCHEMES),
    "accepted_cladding_codes": list(SUPPORTED_CLADDINGS),
    "sources": {
        "vector1_2015": {
            "kind": "historical_manufacturer_album", "manufacturer_id": "vector",
            "issuer_as_printed": "ООО «Вектор групп»", "series": "Вектор-1", "edition_year": 2015,
            "private_artifact": "atspec-testdata/docs/facades_atr/ATR_Vector1_3.15_KG_KP_2015.pdf",
            "public_summary": "Facades/docs/kb/atr_vector1_2015.md", "pdf_pages": 109,
            "edition_note": "3.15 присутствует в имени файла; не самостоятельное подтверждение редакции.",
        },
        "vector5_2017": {
            "kind": "historical_manufacturer_album", "manufacturer_id": "vector",
            "issuer_as_printed": "ООО «Вектор фасад»", "series": "Вектор-5", "edition_year": 2017,
            "private_artifact": "atspec-testdata/docs/facades_atr/ATR_Vector5_AKP_MK_2017.pdf",
            "public_summary": "Facades/docs/kb/atr_vector5_2017.md", "pdf_pages": 139,
            "edition_note": "Опечатка Вектор-2 в ПЗ не меняет идентичность альбома Вектор-5.",
        },
        "nordfox_mlk_2016": {
            "kind": "historical_manufacturer_album", "manufacturer_id": "nordfox",
            "issuer_as_printed": "ООО «ТЕХНОСТАЙЛ»", "series": "MLK-v-300",
            "edition_year": 2016, "edition_label": "v3.76",
            "private_artifact": "atspec-testdata/docs/facades_atr/ATR_NordFOX_MLKv300_v3.76_2016.pdf",
            "public_summary": "Facades/docs/kb/atr_nordfox_mlk_2016.md", "pdf_pages": 93,
        },
        "vector_web_2026": {
            "kind": "historical_marketing_snapshot", "observed_at": "2026-07-18",
            "public_summary": "Facades/docs/KB_VECTOR_FASAD.md",
            "authority_note": "Таксономия сайта не заменяет редакцию АТР и не задаёт расчётные пределы.",
        },
        "project_a_2018": {
            "kind": "private_project_example", "edition_year": 2018,
            "public_summary": "Facades/docs/kb/projects_rules.md",
            "review": "docs/atr_review_3009/Project_vs_rules.md",
            "authority_note": "Анонимизированный проект A; значения относятся к его исходным и изделиям.",
        },
        "project_b_2026": {
            "kind": "private_project_example", "edition_year": 2026,
            "public_summary": "Facades/docs/kb/projects_rules.md",
            "authority_note": "Анонимизированный проект B, Standart/КАФТ; не универсальный альбом.",
        },
        "german_frame_2026": {
            "kind": "recorded_project_workflow_requirement", "recorded_at": "2026-07-26",
            "public_summary": "AFrame/engine/systems.json",
            "authority_note": "Происхождение правил зафиксировано в _src/_comment; это ТЗ, не АТР.",
        },
        "german_tile_2026": {
            "kind": "recorded_project_workflow_requirement", "recorded_at": "2026-09-29",
            "public_summary": "AFrame/docs/NEXT.md",
            "locator": "Записи 29.09b, 29.09c, 29.09j, 29.09l, 29.09n",
            "authority_note": "Шины и их геометрия по ответам Германа; марка и узел изделия по проекту.",
        },
        "implementation_scope_2026": {
            "kind": "implementation_review", "public_summary": "docs/fixes_3009/Domain.md",
            "authority_note": "Границы реализации, включая frame-only АКП и неподтверждённый НСП-2.",
        },
    },
    "manufacturers": {
        "vector": {"brand": "Вектор", "frame_material_family": "steel",
                   "source_ids": ["vector1_2015", "vector5_2017"]},
        "nordfox": {"brand": "NordFOX", "frame_material_family": "aluminium",
                    "source_ids": ["nordfox_mlk_2016"], "implementation_status": "unsupported"},
    },
    "album_types": {
        "vector1_2015_type1": {
            "source_id": "vector1_2015", "album_type": 1, "pdf_page": 18, "sheet": "4",
            "description": "Вертикальная, Г/Т/НГ", "code_scheme": "vertical",
            "correspondence": "partial", "missing": "Нет полной матрицы профилей/узлов ТП и НГ альбома.",
        },
        "vector1_2015_type2": {
            "source_id": "vector1_2015", "album_type": 2, "pdf_page": 29, "sheet": "4",
            "sheet_note": "Повтор номера 4 сохранён по штампу оригинала.",
            "description": "Вертикальная, С/Омега, П-образный КП", "code_scheme": "vertical",
            "correspondence": "partial", "missing": "Нет самостоятельной матрицы КП/СП и узлов типа 2.",
        },
        "vector1_2015_type3": {
            "source_id": "vector1_2015", "album_type": 3, "pdf_page": 39, "sheet": "6",
            "description": "Ортогональная неусиленная", "code_scheme": "ortho",
            "correspondence": "partial", "missing": "Геометрическая схема не подтверждает весь состав узлов АТР.",
        },
        "vector1_2015_type4": {
            "source_id": "vector1_2015", "album_type": 4, "pdf_page": 52, "sheet": "7",
            "description": "Ортогональная усиленная: НГП + НСП/НШП + вставки В/ВС",
            "code_scheme": "interfloor", "correspondence": "partial",
            "missing": "Текущий НГП→НСП каркас лишь частично соответствует; комплект вставок и узлов не замкнут.",
        },
        "vector1_2015_type5": {
            "source_id": "vector1_2015", "album_type": 5, "pdf_page": 61, "sheet": "8",
            "description": "Самостоятельная вертикальная усиленная схема КПК + НСП",
            "code_scheme": None, "correspondence": "unsupported",
            "missing": "Нет генератора/UI типа 5; не подменять типом 4 или кодом interfloor.",
        },
        "vector5_2017_type1": {
            "source_id": "vector5_2017", "album_type": 1, "pdf_page": 19, "sheet": "4",
            "description": "Вертикальная с Г/Т-профилем", "code_scheme": "vertical", "correspondence": "partial",
            "missing": "Каркасная топология не подтверждает выбранный узел АКП.",
        },
        "vector5_2017_type2": {
            "source_id": "vector5_2017", "album_type": 2, "pdf_page": 29, "sheet": "5",
            "description": "Вертикальная с С/Омега-профилем", "code_scheme": "vertical", "correspondence": "partial",
            "missing": "Нет полной самостоятельной матрицы профилей и креплений типа 2.",
        },
        "vector5_2017_type3": {
            "source_id": "vector5_2017", "album_type": 3, "pdf_page": 40, "sheet": "6",
            "description": "Ортогональная неусиленная", "code_scheme": "ortho", "correspondence": "partial",
            "missing": "Геометрическая схема не подтверждает весь комплект узлов.",
        },
        "vector5_2017_type4": {
            "source_id": "vector5_2017", "album_type": 4, "pdf_page": 46, "sheet": "7",
            "description": "Ортогональная усиленная НГП + НСП/НШП + В/ВС", "code_scheme": "interfloor",
            "correspondence": "partial", "missing": "Полный состав вставок, закреплений и узлов АКП не реализован.",
        },
        "vector5_2017_type5": {
            "source_id": "vector5_2017", "album_type": 5, "pdf_page": 55, "sheet": "8",
            "description": "Вертикальная усиленная, прямое опирание НСП на КР1/КПК без НГП",
            "code_scheme": None, "correspondence": "unsupported", "missing": "Нет самостоятельного генератора/UI типа 5.",
        },
    },
    "source_rules": {
        "vector1_gap_reinforced_nodes": {
            "source_id": "vector1_2015", "locators": [
                {"pdf_page": 53, "sheet": "7.1"}, {"pdf_page": 55, "sheet": "7.3"},
                {"pdf_page": 62, "sheet": "8.1"}, {"pdf_page": 64, "sheet": "8.3"}],
            "statement": "10 мм между торцами направляющих на этих усиленных узлах; не общее правило всех типов.",
            "implemented_as_complete_node": False,
        },
        "vector1_kpk_dimension": {
            "source_id": "vector1_2015", "locators": [{"pdf_page": 62, "sheet": "8.1"}, {"pdf_page": 64, "sheet": "8.3"}],
            "statement": "200 мм от верхнего торца нижнего НСП до верхней полки КПК; не шаг полок кронштейна.",
            "implemented_as_complete_node": False,
        },
        "vector1_fire_opening_clamps": {
            "source_id": "vector1_2015", "locators": [{"pdf_page": 103, "sheet": "10.5"}],
            "statement": "Условное дополнительное крепление над проёмом: 650 вверх, 300 за грань; условие >350 по этому узлу/пожарному заключению.",
            "universal_numeric_rule": False, "implemented_as_complete_node": False,
        },
        "vector1_cladding_variants": {
            "source_id": "vector1_2015", "locators": [{"pdf_page": 108, "sheet": "11.1"}, {"pdf_page": 109, "sheet": "11.2"}],
            "statement": "Видимые/скрытые кляммеры, кайлы и крепления керамических плит — разные узлы.",
            "implemented_as_complete_node": False,
        },
        "vector5_acp_variants": {
            "source_id": "vector5_2017", "locators": [{"pdf_page": 135, "sheet": "11.1"}],
            "statement": "Восемь вариантов крепления АКП; салазки/икли/пластины и прямое крепление не заменяются кляммерами КГ.",
            "implemented_as_complete_node": False,
        },
        "nordfox_fixed_sliding": {
            "source_id": "nordfox_mlk_2016", "locators": [{"pdf_page": p, "sheet": str(p)} for p in (22, 24, 26, 27, 30)],
            "statement": "Фиксированные и подвижные крепления; не более одной фиксированной опоры на направляющую, условия по расчёту.",
            "implemented_as_complete_node": False,
        },
        "nordfox_direct_interfloor": {
            "source_id": "nordfox_mlk_2016", "locators": [{"pdf_page": p, "sheet": str(p)} for p in (81, 82, 83, 84, 85)],
            "statement": "UFOX/UTFOX непосредственно несут DT/H; это не передача нагрузки через Вектор НГП→НСП.",
            "implemented_as_complete_node": False,
        },
    },
    "presets": {
        "Вектор-1": {
            "registry_id": "legacy_vector1_project_a", "provenance": "historical_project_preset",
            "source_ids": ["project_a_2018", "german_frame_2026"],
            "manufacturer_contract": False,
        },
        "Standart": {
            "registry_id": "legacy_standart_geometry", "provenance": "legacy_project_geometry_preset",
            "source_ids": ["project_b_2026", "german_frame_2026", "implementation_scope_2026"],
            "manufacturer_contract": False,
            "note": "Standart — исторический геометрический пресет проекта B/КАФТ с позднейшими рабочими правилами. Он не подтверждает полный комплект КАФТ или Вектора. Штатный UI при расчётной вертикальной схеме явно передаёт Вектор-1 через SysOverride.",
        },
        "Межэтажная": {
            "registry_id": "german_interfloor_ngp_nsp", "provenance": "recorded_workflow_requirement",
            "source_ids": ["german_frame_2026", "implementation_scope_2026"], "manufacturer_contract": False,
        },
        "Ортогональная": {
            "registry_id": "german_orthogonal", "provenance": "recorded_workflow_requirement",
            "source_ids": ["german_frame_2026", "implementation_scope_2026"], "manufacturer_contract": False,
        },
    },
    "historical_values": [{
        "source_id": "project_a_2018", "locators": [{"pdf_page": 20, "sheet": "3.1"}, {"pdf_page": 59, "sheet": "расчёт 9/9"}],
        "bracket_spacing_regular_mm": 1200, "bracket_spacing_corner_mm": 800, "tile_joint_axis_mm": 608,
        "meaning": "Величины конкретного проекта, сохранённые в ручном пресете; не универсальные пределы или подтверждение нового объекта.",
        "design_limits": False,
    }],
    "cladding": {
        "porcelain": {"attachment_scope": "porcelain_clamps_geometry", "source_ids": ["vector1_2015", "implementation_scope_2026"],
                      "complete_manufacturer_attachment": False, "missing": ["other_porcelain_nodes", "fire_opening_reinforcement"]},
        "composite": {"attachment_scope": "frame_only_attachment_unimplemented", "source_ids": ["vector5_2017", "implementation_scope_2026"],
                      "complete_manufacturer_attachment": False, "missing": ["acp_attachment_node"]},
        "clinker": {"attachment_scope": "tile_rail_geometry_by_workflow", "source_ids": ["german_tile_2026"],
                    "complete_manufacturer_attachment": False, "missing": ["vector4_album", "tile_product_connection_model"]},
        "concrete": {"attachment_scope": "tile_rail_geometry_by_workflow", "source_ids": ["german_tile_2026"],
                     "complete_manufacturer_attachment": False, "missing": ["vector4_album", "tile_product_connection_model"]},
    },
    "known_missing": {
        "current_vector_album": "Нет актуального АТР для подтверждения современной типизации, номенклатуры и узлов.",
        "vector4_album": "АТР Вектор-4 не получен; шины клинкера/бетона не объявляются реализацией его узлов.",
        "confirmed_nsp2_section": "Не установлено однозначное соответствие НСП-2 и расчётного сечения.",
        "fixed_sliding_supports": "Нет полной модели неподвижных/подвижных опор и температурной кинематики каждого узла.",
        "thermal_movement_design": "Геометрический зазор стыка не равен проверке температурных перемещений/закрепления.",
        "building_movement_joints": "Нет полного проектного решения деформационных швов здания и сопряжений систем.",
        "fire_opening_reinforcement": "Условные пожарные усиления/дополнительные кляммеры над проёмами по выбранному узлу не генерируются.",
        "full_opening_corner_nodes": "Обход проёмов геометрией не является полным узлом откоса/короба/угла/цоколя/парапета.",
        "anchor_substrate_tests": "Испытания анкеров в фактическом основании и инженерное утверждение объекта вне автоматизации.",
        "complete_fastener_bom": "Не заявлен полный комплект всех вставок, крепежа, термопрокладок и сопряжений АТР.",
        "other_porcelain_nodes": "Скрытые, кейловые и иные варианты КГ не покрываются общим режимом кляммеров.",
        "acp_attachment_node": "Не выбран и не реализован узел навески/фиксации конкретной АКП-кассеты.",
        "tile_product_connection_model": "Нет подтверждённой модели сечения, крепления и несущей способности конкретной шины/плитки.",
        "nordfox_generator": "NordFOX — отдельная алюминиевая система; её генератор и расчётные узлы не реализованы.",
    },
}

_COMMON_MISSING = ["fixed_sliding_supports", "thermal_movement_design", "building_movement_joints",
                   "full_opening_corner_nodes", "anchor_substrate_tests", "complete_fastener_bom"]


def registry_snapshot():
    """Independent copy: callers cannot rewrite the canonical registry."""
    return copy.deepcopy(REGISTRY)


def resolve_layout_contract(req, system, sub):
    """Validate explicit preset identity and describe requested, not proven, scope.

    req is the original request; system is the resolved legacy preset (may be an
    empty dict before load_system); sub is the normalized geometry scheme code.
    Numeric values and calculation-method compatibility remain the planner's job.
    """
    raw = req.get("system")
    # Match frame_plan's load_system(req.get("system") or "Standart"):
    # an empty dict selects the legacy default; a nonempty unnamed dict is custom.
    custom = isinstance(raw, dict) and bool(raw) and not raw.get("name")
    name = raw.get("name") if isinstance(raw, dict) else raw
    if custom:
        name = None
        preset = {"registry_id": "custom_unnamed", "provenance": "user_defined_geometry_parameters",
                  "source_ids": [], "manufacturer_contract": False}
    else:
        name = name or "Standart"
        if not isinstance(name, str) or name not in REGISTRY["presets"]:
            return {"ok": False, "error_code": "E_SYSTEM_UNSUPPORTED",
                    "error": "Именованная система %r не поддерживается AFrame. Доступны: %s. "
                             "Пользовательские параметры без имени не подтверждают систему производителя."
                             % (name, ", ".join(REGISTRY["presets"]))}
        preset = REGISTRY["presets"][name]
    if sub not in SUPPORTED_SCHEMES:
        return {"ok": False, "error_code": "E_LAYOUT_SCHEME_UNSUPPORTED",
                "error": "Схема расстановки %r не поддерживается. Допустимы: %s. Тип 5 и прямое межэтажное опирание не реализованы."
                         % (sub, ", ".join(SUPPORTED_SCHEMES))}
    cladding = str(req.get("cladding") or "porcelain").strip().lower()
    if cladding not in SUPPORTED_CLADDINGS:
        return {"ok": False, "error_code": "E_CLADDING_UNSUPPORTED",
                "error": "Облицовка %r не поддерживается. Допустимы: %s." % (cladding, ", ".join(SUPPORTED_CLADDINGS))}
    parts = str(req.get("parts") or "all").strip().lower()
    candidates = [key for key, value in REGISTRY["album_types"].items() if value["code_scheme"] == sub] if not custom else []
    attachment = REGISTRY["cladding"].get(cladding, {})
    missing = list(_COMMON_MISSING) + list(attachment.get("missing", []))
    if not custom:
        missing.append("current_vector_album")
    if sub == "interfloor":
        missing.append("confirmed_nsp2_section")
    sources = list(preset["source_ids"])
    if not custom:
        sources += list(attachment.get("source_ids", []))
        sources += [REGISTRY["album_types"][key]["source_id"] for key in candidates]
    contract = {
        "schema": "aframe_layout_contract/1", "registry_revision": REGISTRY_REVISION,
        "registry_id": preset["registry_id"], "requested_system_name": name,
        "preset_provenance": preset["provenance"], "preset_overrides_present": isinstance(raw, dict) and any(k != "name" for k in raw),
        "manufacturer_id": None, "series": None, "album_edition": None, "approved_node_id": None,
        "identity_note": "Выбранный legacy пресет не задаёт утверждённую комбинацию производителя, серии, редакции и узла.",
        "code_scheme": sub, "album_type_candidates": candidates,
        "album_correspondence": "not_assigned" if custom else ("partial" if candidates else "unsupported"),
        "cladding": cladding, "requested_parts": parts,
        "attachment_scope": attachment.get("attachment_scope", "unknown"),
        "calculation_requested": req.get("calc") is not None,
        "manufacturer_compliance": "not_asserted", "design_limits_from_preset": False,
        "source_ids": list(dict.fromkeys(sources)), "known_missing": list(dict.fromkeys(missing)),
    }
    return {"ok": True, "contract": contract}


def declared_scope(contract, has_openings=False):
    """Output metadata and conditional notes; does not certify a successful run."""
    metadata = copy.deepcopy(contract)
    metadata["has_openings"] = bool(has_openings)
    metadata["scope"] = "custom_geometry" if contract["registry_id"] == "custom_unnamed" else "partial_frame_layout"
    metadata["frame_geometry_requested"] = contract["requested_parts"] != "clamps"
    metadata["cladding_attachment_requested"] = contract["requested_parts"] != "frame"
    notes = ["Результат ограничен геометрией выбранной схемы и выполненными расчётными проверками; полный комплект узлов АТР и соответствие системы производителя не подтверждаются."]
    if contract["registry_id"] == "legacy_standart_geometry":
        notes.append(REGISTRY["presets"]["Standart"]["note"])
    if contract["registry_id"] == "custom_unnamed":
        notes.append("Пользовательские параметры без имени: производитель, серия, редакция АТР и узел не назначены.")
    if not contract["calculation_requested"]:
        notes.append("Ручные шаги/исторический пресет не являются расчётными пределами и не подтверждают несущую способность нового объекта.")
    if contract["cladding"] == "composite":
        notes.append("АКП: выдаётся только поддержанная часть каркаса; крепление конкретной кассеты не реализовано.")
    if contract["cladding"] in ("clinker", "concrete"):
        notes.append("Шины плитки размещаются по рабочему ТЗ Германа; АТР Вектор-4 отсутствует, узел и характеристики конкретной шины требуют отдельного подтверждения.")
    if has_openings and contract["cladding"] == "porcelain":
        notes.append("КГ с проёмами: условное пожарное усиление и дополнительные кляммеры по утверждённому проектному узлу не сформированы. Условие одного листа АТР не применяется ко всем изделиям.")
    if contract["code_scheme"] == "interfloor":
        notes.append("Схема НГП→НСП лишь частично соответствует типу 4 старого альбома; самостоятельный тип 5 КПК→НСП не реализован.")
    return {"metadata": metadata, "notes": notes}


if __name__ == "__main__":
    import argparse
    from pathlib import Path
    parser = argparse.ArgumentParser(description="Export the non-executable audit snapshot of the canonical registry")
    parser.add_argument("--export-catalog", type=Path, required=True)
    args = parser.parse_args()
    args.export_catalog.write_text(json.dumps(registry_snapshot(), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
