using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Script.Serialization;
using AFramePlugin;
using Autodesk.AutoCAD.DatabaseServices;
using Autodesk.AutoCAD.EditorInput;
using Autodesk.AutoCAD.ApplicationServices;
using FacadeSafety;
using Store=FacadeSafety.FacadeProjectParameterStore;
using Forms=System.Windows.Forms;

internal static class CommandIntegrationProbe {
 static readonly JavaScriptSerializer Json=new JavaScriptSerializer { MaxJsonLength=int.MaxValue };
 static readonly List<object> Cases=new List<object>();
 static int failures; static FrameSolutionSelection choice;
 static void Need(bool value,string reason){if(!value)throw new InvalidOperationException(reason);}
 static void Check(string name,Action action){try{action();Cases.Add(new{name,status="PASS"});}catch(Exception e){failures++;Cases.Add(new{name,status="FAIL",reason=e.Message});Console.WriteLine("FAIL "+name+": "+e.Message);}}
 static Document Fresh(){var doc=new Document();Application.DocumentManager.MdiActiveDocument=doc; Application.DialogCalls=0;Application.Dialog=f=>Forms.DialogResult.Cancel;ZoneGeometryGuard.Zones.Clear();ZoneGeometryGuard.Calls=0;ProjectCadCounters.Reset();return doc;}
 static Store.Record ReadProject(Document doc){using(var tr=new Transaction(doc.Database))return Store.ReadProject(tr,doc.Database);}
 static Store.Record ReadZone(Document doc,Hatch h){using(var tr=new Transaction(doc.Database))return Store.ReadZone(tr,h);}
 static FrameProjectParameters SeedProject(Document doc,double offset=230){var selected=choice.Clone();selected.geometry.cladding_front_offset_mm=offset;var previous=ReadProject(doc);var p=FrameProjectParameters.CreateNext(previous.Present?FrameProjectParameters.FromDict(previous.Payload):null,selected,"11111111111111111111111111111111");using(var tr=new Transaction(doc.Database)){Store.WriteProject(tr,doc.Database,previous,p.ToDict());tr.Commit();}return p;}
 static Hatch Zone(Document doc,string name){var h=doc.Database.Add(new Hatch());ZoneGeometryGuard.Zones[h.ObjectId]=new ZoneGeometryResult{Ok=true,ZoneId=name,Fingerprint="geometry:"+name,HatchId=h.ObjectId};return h;}
 static MText Mark(Document doc,Hatch h){var mark=doc.Database.Add(new MText());ZoneGeometryGuard.Zones[mark.ObjectId]=ZoneGeometryGuard.Zones[h.ObjectId];return mark;}
 static void Select(Document doc,params Entity[] entities){var set=new SelectionSet();foreach(var e in entities)set.Items.Add(new SelectedObject{ObjectId=e.ObjectId});doc.Editor.Selection=new PromptSelectionResult{Status=PromptStatus.OK,Value=set};}
 static FrameZoneParameters Bind(Document doc,Hatch h,FrameProjectParameters p,double? offset=null){var before=ReadZone(doc,h);var overrides=new Dictionary<string,FrameParameterOverride>();if(offset.HasValue)overrides.Add("geometry.cladding_front_offset_mm",FrameParameterOverride.Set(offset.Value));var next=FrameZoneParameters.CreateNext(before.Present?FrameZoneParameters.FromDict(before.Payload):null,p,overrides);using(var tr=new Transaction(doc.Database)){Store.WriteZone(tr,h,ZoneGeometryGuard.Zones[h.ObjectId].Fingerprint,before,next.ToDict());tr.Commit();}return next;}
 static void ResetObservation(Document doc){ProjectCadCounters.Reset();doc.Editor.Messages="";Application.DialogCalls=0;doc.LockCalls=0;ZoneGeometryGuard.Calls=0;}
 static void ExpectRefusal(Action action,string label){bool refused=false;try{action();}catch(InvalidOperationException){refused=true;}Need(refused,label+": expected refusal");}
 static FrameProjectOperation Observe(Document d,IList<Hatch> hatches,IDictionary<ObjectId,Dictionary<string,object>> previous=null){var op=new FrameProjectOperation();using(var tr=new Transaction(d.Database)){foreach(var h in hatches){Dictionary<string,object> old=null;if(previous!=null)previous.TryGetValue(h.ObjectId,out old);var zone=ZoneGeometryGuard.Zones[h.ObjectId];op.Observe(tr,d.Database,h,zone.Fingerprint,zone.ZoneId,old);}tr.Commit();}return op;}
 static FrameSettings Settings(){return new FrameSettings { Steps="manual",Profile="ГП-60-40" };}
 static void Refused(Document doc,string contains){Need(doc.Editor.Messages.Contains(contains),"expected precise refusal: "+contains+"; observed "+doc.Editor.Messages);Need(!doc.Editor.Messages.Contains("Параметры зон сохранены"),"refusal reported success");}
 public static int Main(string[] args){choice=FrameSolutionSelection.FromDict(Json.DeserializeObject(File.ReadAllText(args[0])));
  Check("actual project command cancel creates no NOD or write transaction",()=>{var d=Fresh();new FrameProjectCommand().Project();Need(!ReadProject(d).Present&&d.LockCalls==0&&ProjectCadCounters.DataWrites==0,"cancel wrote project");});
  Check("actual project command explicit bootstrap then no-op preserves raw record",()=>{var d=Fresh();Application.Dialog=f=>{((FrameProjectForm)f).Result=FrameProjectParameters.CreateNext(null,choice);return Forms.DialogResult.OK;};new FrameProjectCommand().Project();var before=ReadProject(d);Need(before.Present&&FrameProjectParameters.FromDict(before.Payload).revision==1&&d.LockCalls==1,"bootstrap failed");ResetObservation(d);Application.Dialog=f=>{var form=(FrameProjectForm)f;form.Result=form.Previous.Clone();return Forms.DialogResult.OK;};new FrameProjectCommand().Project();Need(ReadProject(d).RecordDigest==before.RecordDigest&&ProjectCadCounters.DataWrites==0,"no-op changed revision or storage");});
  Check("actual project command rejects concurrent mutation after editor",()=>{var d=Fresh();SeedProject(d);Application.Dialog=f=>{var form=(FrameProjectForm)f;form.Result=FrameProjectParameters.CreateNext(form.Previous,choice);SeedProject(d,330);return Forms.DialogResult.OK;};new FrameProjectCommand().Project();Refused(d,"Параметры проекта изменились после открытия окна");Need(FrameProjectParameters.FromDict(ReadProject(d).Payload).defaults.geometry.cladding_front_offset_mm==330,"CAS overwrote concurrent project");});
  Check("actual project command malformed accepted result creates nothing",()=>{var d=Fresh();Application.Dialog=f=>Forms.DialogResult.OK;new FrameProjectCommand().Project();Refused(d,"Нет подтверждённых параметров проекта");Need(!ReadProject(d).Present&&d.LockCalls==0,"empty result created project");});
  Check("actual zone command rejects missing project before editor",()=>{var d=Fresh();var h=Zone(d,"A");Select(d,h);new FrameProjectCommand().ZoneParameters();Refused(d,"Сначала явно задайте параметры проекта");Need(Application.DialogCalls==0&&!ReadZone(d,h).Present,"implicit bootstrap");});
  Check("actual zone command cancel preserves absent bindings",()=>{var d=Fresh();SeedProject(d);var h=Zone(d,"A");Select(d,h);ResetObservation(d);new FrameProjectCommand().ZoneParameters();Need(!ReadZone(d,h).Present&&ProjectCadCounters.DataWrites==0&&d.LockCalls==0,"zone cancel mutated drawing");});
  Check("actual zone command de-duplicates canonical hatch plus aliases",()=>{var d=Fresh();var p=SeedProject(d);var h=Zone(d,"A");var mark=Mark(d,h);Select(d,mark,h,mark);ResetObservation(d);Application.Dialog=f=>{var form=(FrameZoneParametersForm)f;form.Result=FrameZoneParameters.CreateNext(null,form.Project,new Dictionary<string,FrameParameterOverride>());return Forms.DialogResult.OK;};new FrameProjectCommand().ZoneParameters();Need(ReadZone(d,h).Present&&mark.ExtensionDictionary.IsNull&&ProjectCadCounters.DataWrites==1,"binding copied to alias or written twice");Need(ZoneGeometryGuard.Calls==2&&ProjectCadCounters.ModelSpaceReads==0,"selection performed unbounded geometry reads");});
  Check("actual zone command refuses mixed bound and unbound intent before editor",()=>{var d=Fresh();var p=SeedProject(d);var a=Zone(d,"A");var b=Zone(d,"B");Bind(d,a,p);Select(d,a,b);ResetObservation(d);new FrameProjectCommand().ZoneParameters();Refused(d,"разные намерения");Need(Application.DialogCalls==0&&!ReadZone(d,b).Present&&ProjectCadCounters.DataWrites==0,"mixed intent silently inherited");});
  Check("actual zone command refuses equal effective values with different intent",()=>{var d=Fresh();var p=SeedProject(d);var a=Zone(d,"A");var b=Zone(d,"B");Bind(d,a,p);Bind(d,b,p,230);Select(d,a,b);ResetObservation(d);new FrameProjectCommand().ZoneParameters();Refused(d,"разные намерения");Need(Application.DialogCalls==0&&ProjectCadCounters.DataWrites==0,"editor replaced different origins");});
  Check("actual zone command rejects unverified carrier",()=>{var d=Fresh();SeedProject(d);var h=d.Database.Add(new Hatch());Select(d,h);ResetObservation(d);new FrameProjectCommand().ZoneParameters();Refused(d,"carrier not a verified ATFZONE");Need(Application.DialogCalls==0&&!ReadZone(d,h).Present,"noncanonical hatch bound");});
  Check("actual zone command rejects project change during editor without binding writes",()=>{var d=Fresh();SeedProject(d);var h=Zone(d,"A");Select(d,h);Application.Dialog=f=>{var form=(FrameZoneParametersForm)f;form.Result=FrameZoneParameters.CreateNext(null,form.Project,new Dictionary<string,FrameParameterOverride>());SeedProject(d,350);return Forms.DialogResult.OK;};new FrameProjectCommand().ZoneParameters();Refused(d,"Параметры проекта изменились");Need(!ReadZone(d,h).Present,"stale project bound");});
  Check("actual zone command rejects changed geometry after editor",()=>{var d=Fresh();SeedProject(d);var h=Zone(d,"A");Select(d,h);ResetObservation(d);Application.Dialog=f=>{var form=(FrameZoneParametersForm)f;form.Result=FrameZoneParameters.CreateNext(null,form.Project,new Dictionary<string,FrameParameterOverride>());ZoneGeometryGuard.Zones[h.ObjectId].Fingerprint="changed-after-dialog";return Forms.DialogResult.OK;};new FrameProjectCommand().ZoneParameters();Refused(d,"изменилась после открытия окна");Need(!ReadZone(d,h).Present&&ProjectCadCounters.DataWrites==0,"stale geometry bound");});
  Check("actual zone command rolls first binding back when second CAS fails",()=>{var d=Fresh();var p=SeedProject(d);var a=Zone(d,"A");var b=Zone(d,"B");Bind(d,a,p);Bind(d,b,p);var before=ReadZone(d,a).RecordDigest;Select(d,a,b);Application.Dialog=f=>{var form=(FrameZoneParametersForm)f;form.Result=FrameZoneParameters.CreateNext(form.Previous,form.Project,new Dictionary<string,FrameParameterOverride>{{"geometry.cladding_front_offset_mm",FrameParameterOverride.Set(300)}});Bind(d,b,p,340);return Forms.DialogResult.OK;};new FrameProjectCommand().ZoneParameters();Refused(d,"Параметры зоны изменились после открытия окна");Need(ReadZone(d,a).RecordDigest==before,"first binding committed despite second CAS failure");Need(Convert.ToDouble(FrameZoneParameters.FromDict(ReadZone(d,b).Payload).overrides["geometry.cladding_front_offset_mm"].value)==340,"concurrent second binding lost");});
  Check("actual zone command explicitly detaches without altering project",()=>{var d=Fresh();var p=SeedProject(d);var h=Zone(d,"A");Bind(d,h,p);var before=ReadProject(d).RecordDigest;Select(d,h);Application.Dialog=f=>Forms.DialogResult.OK;new FrameProjectCommand().ZoneParameters();Need(!ReadZone(d,h).Present&&ReadProject(d).RecordDigest==before,"detach changed project or kept binding");Need(d.Editor.Messages.Contains("не становятся локальным решением"),"detach omits snapshot boundary");});
  Check("actual zone command explicit rebind confirms new generation",()=>{var d=Fresh();var p=SeedProject(d);var h=Zone(d,"A");Bind(d,h,p);var before=ReadZone(d,h);ZoneGeometryGuard.Zones[h.ObjectId].Fingerprint="geometry:A:new";Select(d,h);Application.Dialog=f=>{var form=(FrameZoneParametersForm)f;Need(form.Scope.Contains("новое поколение"),"editor hides rebind");form.Result=form.Previous.Clone();return Forms.DialogResult.OK;};new FrameProjectCommand().ZoneParameters();var after=ReadZone(d,h);Need(after.RecordDigest!=before.RecordDigest&&after.ZoneFingerprint=="geometry:A:new","generation not explicitly renewed");});
  Check("actual zone command group keeps independent revision history",()=>{var d=Fresh();var p=SeedProject(d);var a=Zone(d,"A");var b=Zone(d,"B");Bind(d,a,p);Bind(d,b,p,310);Bind(d,b,p);Need(FrameZoneParameters.FromDict(ReadZone(d,a).Payload).revision==1&&FrameZoneParameters.FromDict(ReadZone(d,b).Payload).revision==2,"bad fixture");Select(d,a,b);Application.Dialog=f=>{var form=(FrameZoneParametersForm)f;form.Result=FrameZoneParameters.CreateNext(form.Previous,form.Project,new Dictionary<string,FrameParameterOverride>{{"geometry.cladding_front_offset_mm",FrameParameterOverride.Set(300)}});return Forms.DialogResult.OK;};new FrameProjectCommand().ZoneParameters();Need(FrameZoneParameters.FromDict(ReadZone(d,a).Payload).revision==2&&FrameZoneParameters.FromDict(ReadZone(d,b).Payload).revision==3,"group collapsed per-zone revision");});
  Check("actual generation operation resolves equal values while retaining per-owner origins",()=>{var d=Fresh();var p=SeedProject(d);var a=Zone(d,"A");var b=Zone(d,"B");Bind(d,a,p);Bind(d,b,p,230);var op=Observe(d,new[]{a,b});op.ValidateGroup();var fs=Settings();op.Apply(fs);op.ValidateSelectedSettings(fs);var map=new Dictionary<ObjectId,ObjectId>{{a.ObjectId,a.ObjectId},{b.ObjectId,b.ObjectId}};var first=FrameSettings.FromDict(op.SettingsForOwner(fs,a.ObjectId,map));var second=FrameSettings.FromDict(op.SettingsForOwner(fs,b.ObjectId,map));Need(first.ProjectParametersContext.zone.owner_handle==a.Handle.ToString()&&second.ProjectParametersContext.zone.owner_handle==b.Handle.ToString(),"first zone context copied to every owner");Need(first.ProjectParametersContext.origins["geometry.cladding_front_offset_mm"]=="project_default"&&second.ProjectParametersContext.origins["geometry.cladding_front_offset_mm"]=="zone_override","different origins lost");Need(!first.ToDict().ContainsKey("project_parameters_snapshot"),"all-zone map copied into each owner");Need(Json.Serialize(op.Contexts()).Length<20000,"unexpected provenance explosion");Need(!fs.EngineParams(0).ContainsKey("project_parameters_context"),"per-owner provenance leaked into engine input");});
  Check("actual generation operation resolves aliases to canonical owner context",()=>{var d=Fresh();var p=SeedProject(d);var h=Zone(d,"A");var mark=Mark(d,h);Bind(d,h,p);var op=Observe(d,new[]{h});var fs=Settings();op.Apply(fs);var map=new Dictionary<ObjectId,ObjectId>{{mark.ObjectId,h.ObjectId}};var stored=FrameSettings.FromDict(op.SettingsForOwner(fs,mark.ObjectId,map));Need(stored.ProjectParametersContext.zone.owner_handle==h.Handle.ToString(),"alias got independent parameter identity");ExpectRefusal(()=>op.SettingsForOwner(fs,d.Database.Add(new MText()).ObjectId,map),"unmapped owner");});
  Check("actual generation operation ignores obsolete local disagreement only for explicit current project",()=>{var d=Fresh();var p=SeedProject(d);var a=Zone(d,"A");var b=Zone(d,"B");Bind(d,a,p);Bind(d,b,p);var sa=Settings();sa.SolutionSelection=choice.Clone();var sb=Settings();sb.SolutionSelection=choice.Clone();sb.SolutionSelection.geometry.cladding_front_offset_mm=440;var op=Observe(d,new[]{a,b},new Dictionary<ObjectId,Dictionary<string,object>>{{a.ObjectId,sa.ToDict()},{b.ObjectId,sb.ToDict()}});op.ValidateGroup();var fs=sa.Clone();op.Apply(fs);Need(fs.SolutionSelection.geometry.cladding_front_offset_mm==230,"old snapshot overrode current project");ExpectRefusal(()=>op.ValidateClamps(new[]{"A","B"}),"unapplied project clamps");});
  Check("actual generation operation refuses mixed canonical binding and different effective selections",()=>{var d=Fresh();var p=SeedProject(d);var a=Zone(d,"A");var b=Zone(d,"B");Bind(d,a,p);var mixed=Observe(d,new[]{a,b});ExpectRefusal(()=>mixed.ValidateGroup(),"mixed canonical binding");Bind(d,b,p,330);var differing=Observe(d,new[]{a,b});ExpectRefusal(()=>differing.ValidateGroup(),"different effective");});
  Check("actual generation operation permits excluded raw holes but refuses actual raw outer",()=>{var d=Fresh();var p=SeedProject(d);var a=Zone(d,"A");Bind(d,a,p);var op=Observe(d,new[]{a});op.ValidateGroup();op.ValidateGroup(new[]{"A"});ExpectRefusal(()=>op.ValidateGroup(new[]{"A","raw outer B"}),"actual unbound outer");ExpectRefusal(()=>op.ValidateGroup(new[]{"raw outer B"}),"bound root excluded entirely");ExpectRefusal(()=>op.ValidateGroup(new string[0]),"empty actual roots");});
  Check("actual generation operation detaches inherited snapshot but preserves true local choice",()=>{var d=Fresh();var p=SeedProject(d);var h=Zone(d,"A");Bind(d,h,p);var bound=Observe(d,new[]{h});var inherited=Settings();bound.Apply(inherited);var old=inherited.ToDict();using(var tr=new Transaction(d.Database)){Store.ClearZone(tr,h,ZoneGeometryGuard.Zones[h.ObjectId].Fingerprint,Store.ReadZone(tr,h));tr.Commit();}var detached=Observe(d,new[]{h},new Dictionary<ObjectId,Dictionary<string,object>>{{h.ObjectId,old}});detached.Apply(inherited);Need(inherited.SolutionSelection==null&&inherited.ProjectParametersContext==null,"inherited snapshot became local");var local=Settings();local.SolutionSelection=choice.Clone();detached.Apply(local);Need(local.SolutionSelection!=null&&local.ProjectParametersContext==null,"true local 2B1 choice lost");});
  Check("actual generation operation refuses clamps after explicit detach",()=>{var d=Fresh();var p=SeedProject(d);var h=Zone(d,"A");Bind(d,h,p);var bound=Observe(d,new[]{h});var old=Settings();bound.Apply(old);using(var tr=new Transaction(d.Database)){Store.ClearZone(tr,h,ZoneGeometryGuard.Zones[h.ObjectId].Fingerprint,Store.ReadZone(tr,h));tr.Commit();}var detached=Observe(d,new[]{h},new Dictionary<ObjectId,Dictionary<string,object>>{{h.ObjectId,old.ToDict()}});ExpectRefusal(()=>detached.ValidateClamps(new[]{"A"}),"detached inherited rails need full regeneration");});
  Check("actual generation operation refuses detached inherited alias even if canonical metadata is absent",()=>{var d=Fresh();var p=SeedProject(d);var h=Zone(d,"A");var mark=Mark(d,h);Bind(d,h,p);var bound=Observe(d,new[]{h});var saved=Settings();bound.Apply(saved);using(var tr=new Transaction(d.Database)){Store.ClearZone(tr,h,ZoneGeometryGuard.Zones[h.ObjectId].Fingerprint,Store.ReadZone(tr,h));tr.Commit();}var detached=Observe(d,new[]{h});detached.CaptureSavedSettings(new Dictionary<ObjectId,Dictionary<string,object>>{{h.ObjectId,null},{mark.ObjectId,saved.ToDict()}});ExpectRefusal(()=>detached.ValidateClamps(new[]{"A"}),"detached inherited alias needs full regeneration");});
  Check("actual generation operation clamps needs exact dependencies even for equal effective values",()=>{var d=Fresh();var p=SeedProject(d);var h=Zone(d,"A");Bind(d,h,p,230);var first=Observe(d,new[]{h});var saved=Settings();first.Apply(saved);var previous=new Dictionary<ObjectId,Dictionary<string,object>>{{h.ObjectId,saved.ToDict()}};var equal=Observe(d,new[]{h},previous);equal.ValidateClamps(new[]{"A"});SeedProject(d,330);var changed=Observe(d,new[]{h},previous);var fs=Settings();changed.Apply(fs);Need(FrameSolutionSelection.Same(saved.SolutionSelection,fs.SolutionSelection),"fixture changed pinned effective value");ExpectRefusal(()=>changed.ValidateClamps(new[]{"A"}),"changed dependency clamps");});
  Check("actual generation operation clamps checks canonical-linked alias provenance",()=>{var d=Fresh();var p=SeedProject(d);var h=Zone(d,"A");var mark=Mark(d,h);Bind(d,h,p);var first=Observe(d,new[]{h});var saved=Settings();first.Apply(saved);var original=saved.ToDict();var old=new Dictionary<ObjectId,Dictionary<string,object>>{{h.ObjectId,original},{mark.ObjectId,original}};var canonical=new Dictionary<ObjectId,ObjectId>{{h.ObjectId,h.ObjectId},{mark.ObjectId,h.ObjectId}};var roots=new Dictionary<ObjectId,Tuple<string,bool>>{{h.ObjectId,Tuple.Create("A",false)},{mark.ObjectId,Tuple.Create("A",false)}};var same=Observe(d,new[]{h},old);same.CaptureSavedSettings(old,canonical,roots);same.ValidateClamps(new[]{"A"});var changed=saved.Clone();changed.ProjectParametersContext.project.revision++;old[mark.ObjectId]=changed.ToDict();var different=Observe(d,new[]{h},old);different.CaptureSavedSettings(old,canonical,roots);ExpectRefusal(()=>different.ValidateClamps(new[]{"A"}),"alias context disagrees with retained canonical");old[mark.ObjectId]=null;var absent=Observe(d,new[]{h},old);absent.CaptureSavedSettings(old,canonical,roots);absent.ValidateClamps(new[]{"A"});});
  Check("actual generation operation blocks edits of bound effective selection",()=>{var d=Fresh();var p=SeedProject(d);var h=Zone(d,"A");Bind(d,h,p);var op=Observe(d,new[]{h});var fs=Settings();op.Apply(fs);fs.SolutionSelection.geometry.cladding_front_offset_mm=999;ExpectRefusal(()=>op.ValidateSelectedSettings(fs),"edited bound effective");});
  Check("actual generation operation fresh guard rejects project and zone mutation",()=>{var d=Fresh();var p=SeedProject(d);var h=Zone(d,"A");Bind(d,h,p);var op=Observe(d,new[]{h});using(var tr=new Transaction(d.Database)){op.VerifyFresh(tr,d.Database,new Store.ReadContext());tr.Commit();}Bind(d,h,p,310);using(var tr=new Transaction(d.Database))ExpectRefusal(()=>op.VerifyFresh(tr,d.Database,new Store.ReadContext()),"zone changed after editor");op=Observe(d,new[]{h});SeedProject(d,330);using(var tr=new Transaction(d.Database))ExpectRefusal(()=>op.VerifyFresh(tr,d.Database,new Store.ReadContext()),"project changed after editor");});
  Check("actual bound prewrite guard revalidates fresh canonical geometry despite unchanged binding record",()=>{var d=Fresh();var p=SeedProject(d);var h=Zone(d,"A");Bind(d,h,p);var op=Observe(d,new[]{h});var unchanged=ReadZone(d,h).RecordDigest;ZoneGeometryGuard.Zones[h.ObjectId]=new ZoneGeometryResult{Ok=true,ZoneId="A",HatchId=h.ObjectId,Fingerprint="geometry:A:changed-during-dialog"};using(var tr=new Transaction(d.Database))ExpectRefusal(()=>op.VerifyFresh(tr,d.Database,new Store.ReadContext()),"fresh geometry changed without parameter mutation");Need(ReadZone(d,h).RecordDigest==unchanged,"fixture mutated binding rather than geometry");});
  Check("actual generation operation fresh guard detects newly bound previous unbound source",()=>{var d=Fresh();var p=SeedProject(d);var h=Zone(d,"A");var op=Observe(d,new[]{h});Bind(d,h,p);using(var tr=new Transaction(d.Database))ExpectRefusal(()=>op.VerifyFresh(tr,d.Database,new Store.ReadContext()),"unbound became bound");});
  Check("actual generation operation saved baseline is separate from current effective scope",()=>{var d=Fresh();var p=SeedProject(d);var h=Zone(d,"A");Bind(d,h,p);var local=Settings();local.SolutionSelection=choice.Clone();var original=local.ToDict();var op=Observe(d,new[]{h},new Dictionary<ObjectId,Dictionary<string,object>>{{h.ObjectId,original}});op.CaptureSavedSettings(new Dictionary<ObjectId,Dictionary<string,object>>{{h.ObjectId,original}});op.Apply(local);op.VerifySavedSettings(h.ObjectId,original);ExpectRefusal(()=>op.VerifySavedSettings(h.ObjectId,local.ToDict()),"saved metadata mutation");});
  Check("actual prewrite guard rejects changed detached project metadata before normalization",()=>{var d=Fresh();var p=SeedProject(d);var h=Zone(d,"A");Bind(d,h,p);var bound=Observe(d,new[]{h});var saved=Settings();bound.Apply(saved);using(var tr=new Transaction(d.Database)){Store.ClearZone(tr,h,ZoneGeometryGuard.Zones[h.ObjectId].Fingerprint,Store.ReadZone(tr,h));tr.Commit();}var baseline=saved.ToDict();var prior=new Dictionary<ObjectId,Dictionary<string,object>>{{h.ObjectId,baseline}};var detached=Observe(d,new[]{h},prior);detached.CaptureSavedSettings(prior);var changed=saved.Clone();changed.ProjectParametersContext.project.revision++;ActualProjectPrewrite.Metadata.Clear();ActualProjectPrewrite.Metadata[h.ObjectId]=changed.ToDict();var normalized=new FrameSolutionSelectionContext();normalized.Add(null);using(var tr=new Transaction(d.Database)){detached.VerifyFresh(tr,d.Database,new Store.ReadContext());ExpectRefusal(()=>ActualProjectPrewrite.Fresh(detached,tr,new Dictionary<ObjectId,Tuple<string,bool>>{{h.ObjectId,Tuple.Create("A",false)}},new HashSet<ObjectId>{h.ObjectId},new List<string>{"A"},normalized),"changed detached metadata");}});
  Check("actual generation operation uses one project read and one zone record per unique owner",()=>{var d=Fresh();var p=SeedProject(d);var zones=new List<Hatch>();for(int i=0;i<100;i++){var h=Zone(d,"Z"+i);Bind(d,h,p);zones.Add(h);}ProjectCadCounters.Reset();var op=Observe(d,zones.Concat(zones).ToArray());Need(ProjectCadCounters.DataReads==101&&ProjectCadCounters.NodReads==1&&ProjectCadCounters.ModelSpaceReads==0,"nonlinear or repeated reads during resolution");op.ValidateGroup();ProjectCadCounters.Reset();using(var tr=new Transaction(d.Database)){var reads=new Store.ReadContext();op.VerifyFresh(tr,d.Database,reads);foreach(var h in zones)Store.ReadZone(tr,h,null,reads);Need(reads.ZoneReads==100,"same phase duplicate zone parse");tr.Commit();}Need(ProjectCadCounters.DataReads==101&&ProjectCadCounters.NodReads==1&&ProjectCadCounters.ModelSpaceReads==0,"nonlinear freshness reads");});
  var result=new{status=failures==0?"PASS":"FAIL",checks=Cases.Count,failed=failures,cases=Cases,live_autocad_checked=false,scope="Actual complete FrameProjectCommand; actual pure DTO and project store; host/editor/forms/geometry verification doubled; rollback uses explicit in-memory store model"};File.WriteAllText(args[1],Json.Serialize(result));Console.WriteLine("Project parameter commands: "+Cases.Count+" checks, "+failures+" failures");return failures==0?0:1;
 }
}
