using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web.Script.Serialization;
using AFramePlugin;
using Autodesk.AutoCAD.DatabaseServices;
using Autodesk.AutoCAD.Geometry;
using Autodesk.AutoCAD.EditorInput;
using Autodesk.AutoCAD.ApplicationServices;
using FacadeSafety;
using ProjectStore=FacadeSafety.FacadeProjectParameterStore;
using Forms=System.Windows.Forms;

internal static class NodeCadProbe {
 static readonly JavaScriptSerializer Json=new JavaScriptSerializer{MaxJsonLength=int.MaxValue};
 static readonly List<object> Cases=new List<object>();static readonly List<object> Performance=new List<object>();static int failed,rollbackFailurePoints;static FrameSolutionSelection selected;
 sealed class Fixture {
  internal Document Doc;internal Hatch Zone;internal FrameProjectParameters Project;internal FrameZoneParameters Binding;
  internal Database Db {get{return Doc.Database;}}
 }
 static void Need(bool value,string reason){if(!value)throw new InvalidOperationException(reason);}
 static void Check(string name,Action action){try{action();Cases.Add(new{name,status="PASS"});}catch(Exception error){failed++;Cases.Add(new{name,status="FAIL",reason=error.Message});Console.WriteLine("FAIL "+name+": "+error);}}
 static void Refuses(Action action,string reason){bool rejected=false;try{action();}catch(InvalidOperationException){rejected=true;}Need(rejected,reason);}
 static void RefusesCode(Action action,string code){bool rejected=false;try{action();}catch(FrameNodeGeometryException e){Need(e.Code==code,"expected "+code+", got "+e.Code);rejected=true;}Need(rejected,"expected "+code);}
 static void MutateRecord(BlockReference node,Action<Dictionary<string,object>> mutate){var record=Record(node);string raw=string.Concat(record.Values.Where(x=>x.TypeCode==(int)DxfCode.Text).Select(x=>(string)x.Value));var payload=(Dictionary<string,object>)Json.DeserializeObject(raw);mutate(payload);record.Values=record.Values.Where(x=>x.TypeCode!=(int)DxfCode.Text).Concat(new[]{new TypedValue((int)DxfCode.Text,Json.Serialize(payload))}).ToArray();}
 static Fixture Fresh(bool bound=true) {
  var doc=new Document();Application.DocumentManager.MdiActiveDocument=doc;Application.DialogCalls=0;
  Application.Dialog=f=>{var form=(FrameNodeForm)f;form.Result=Input();return Forms.DialogResult.OK;};
  ZoneGeometryGuard.Zones.Clear();ZoneGeometryGuard.Calls=0;var h=doc.Database.Add(new Hatch());
  ZoneGeometryGuard.Zones[h.ObjectId]=new ZoneGeometryResult{Ok=true,ZoneId="Ф-1",Fingerprint="geometry:original",HatchId=h.ObjectId};
  var choice=selected.Clone();choice.geometry.cladding_front_offset_mm=230;choice.geometry.insulation_layers_mm=new List<double>{100,50};
  var p=FrameProjectParameters.CreateNext(null,choice,"11111111111111111111111111111111");
  var z=FrameZoneParameters.CreateNext(null,p,new Dictionary<string,FrameParameterOverride>());
  using(var tr=new Transaction(doc.Database)) {ProjectStore.WriteProject(tr,doc.Database,ProjectStore.ReadProject(tr,doc.Database),p.ToDict());if(bound)ProjectStore.WriteZone(tr,h,"geometry:original",ProjectStore.ReadZone(tr,h),z.ToDict());tr.Commit();}
  var result=new Fixture{Doc=doc,Zone=h,Project=p,Binding=z};SetCreate(result);ProjectCadCounters.Reset();return result;
 }
 static FrameNodeGeometryInput Input(double profile=170){return new FrameNodeGeometryInput{profile_near_face_x_mm=profile,clearance_surface=new FrameNodeClearanceSurface{kind=FrameNodeClearanceSurface.Layers}};}
 static void SetCreate(Fixture f){f.Doc.Editor.Keywords.Clear();f.Doc.Editor.Keywords.Enqueue(new PromptResult{Status=PromptStatus.OK,StringResult="Create"});f.Doc.Editor.Entity=new PromptEntityResult{Status=PromptStatus.OK,ObjectId=f.Zone.ObjectId};f.Doc.Editor.Point=new PromptPointResult{Status=PromptStatus.OK,Value=new Point3d(100,200,0)};}
 static void SetCheck(Fixture f,BlockReference owner){f.Doc.Editor.Messages="";f.Doc.Editor.Keywords.Clear();f.Doc.Editor.Keywords.Enqueue(new PromptResult{Status=PromptStatus.OK,StringResult="Check"});f.Doc.Editor.Entity=new PromptEntityResult{Status=PromptStatus.OK,ObjectId=owner.ObjectId};}
 static List<BlockReference> Nodes(Fixture f){return f.Db.Objects.Values.OfType<BlockReference>().Where(x=>!x.IsErased&&!x.Removed).ToList();}
 static string Dump(Fixture f){var parts=new List<string>();foreach(var pair in f.Db.Objects.OrderBy(x=>x.Key)){var x=pair.Value;parts.Add(pair.Key+":"+x.GetType().FullName+":"+x.IsErased);var dict=x as DBDictionary;if(dict!=null)foreach(var a in dict.Items.OrderBy(a=>a.Key))parts.Add("D"+a.Key+":"+a.Value.Handle);var table=x as SymbolTable;if(table!=null)foreach(var a in table.Items.OrderBy(a=>a.Key))parts.Add("S"+a.Key+":"+a.Value.Handle);var block=x as BlockTableRecord;if(block!=null)parts.Add("B"+string.Join(",",block.Children.Select(a=>a.Handle.ToString()).ToArray()));var xr=x as Xrecord;if(xr!=null)foreach(var a in xr.Values??new TypedValue[0])parts.Add("R"+a.TypeCode+":"+(a.Value is ObjectId?((ObjectId)a.Value).Handle.ToString():Convert.ToString(a.Value,CultureInfo.InvariantCulture)));var e=x as Entity;if(e!=null)parts.Add("E"+e.ExtensionDictionary.Handle);}return string.Join("|",parts.ToArray());}
 static FrameParameterResolution Resolve(Fixture f){using(var tr=new Transaction(f.Db)){var p=ProjectStore.ReadProject(tr,f.Db);var z=ProjectStore.ReadZone(tr,f.Zone);return FrameParameterResolver.Resolve(FrameProjectParameters.FromDict(p.Payload),p.RecordDigest,FrameZoneParameters.FromDict(z.Payload),z.RecordDigest,f.Zone.Handle.ToString(),"Ф-1");}}
 static FrameNodeSnapshot Snapshot(Fixture f,FrameNodeGeometryInput input=null){var resolved=Resolve(f);return FrameNodeSnapshot.Create(resolved.Selection,resolved.Context,input??Input(),"2026-10-01T12:00:00.0000000Z");}
 static FrameNodeSnapshot ExactSnapshot(Fixture f,FrameSolutionSelection choice,FrameNodeGeometryInput input){
  // Preserve the declared typed values at this boundary. The separate command
  // tests below exercise the unchanged legacy resolver and its drift refusal.
  var context=Resolve(f).Context;var project=new FrameProjectParameters{project_id=f.Project.project_id,revision=f.Project.revision+1,defaults=FrameNodeGeometry.CloneSelection(choice)};
  project.content_digest=FrameParameterJson.Hash(new Dictionary<string,object>{{"schema",project.schema},{"project_id",project.project_id},{"defaults",project.defaults.ToDict()}});
  ProjectStore.Record persisted;using(var tr=new Transaction(f.Db)){ProjectStore.WriteProject(tr,f.Db,ProjectStore.ReadProject(tr,f.Db),project.ToDict());persisted=ProjectStore.ReadProject(tr,f.Db);tr.Commit();}
  context.project.revision=project.revision;context.project.content_digest=project.content_digest;context.project.record_digest=persisted.RecordDigest;context.effective_digest=FrameParameterResolver.SelectionDigest(choice);
  return FrameNodeSnapshot.Create(choice,context,input,"2026-10-01T12:00:00.0000000Z");
 }
 static BlockReference CreateSnapshot(Fixture f,FrameNodeSnapshot snapshot){var drawing=FrameNodeDrawingBuilder.Build(snapshot.Result,snapshot.CaptionLines());using(var tr=new Transaction(f.Db)){var node=FrameNodeRenderer.Create(tr,f.Db,drawing,new Point3d(100,200,0));FrameNodeStore.Write(tr,node,f.Zone,"geometry:original",snapshot,"database_mm",f.Db.Insunits,drawing.Digest);tr.Commit();return node;}}
 static long Bits(double value){return BitConverter.DoubleToInt64Bits(value);}
 static BlockReference DirectCreate(Fixture f,FrameNodeGeometryInput input=null){var snapshot=Snapshot(f,input);var drawing=FrameNodeDrawingBuilder.Build(snapshot.Result,snapshot.CaptionLines());using(var tr=new Transaction(f.Db)){var node=FrameNodeRenderer.Create(tr,f.Db,drawing,new Point3d(100,200,0));FrameNodeStore.Write(tr,node,f.Zone,"geometry:original",snapshot,"database_mm",f.Db.Insunits,drawing.Digest);tr.Commit();return node;}}
 static FrameNodeStored Read(Fixture f,BlockReference node){using(var tr=new Transaction(f.Db))return FrameNodeStore.Read(tr,node);}
 static Xrecord Record(BlockReference node){return (Xrecord)((DBDictionary)node.ExtensionDictionary.Item).Items[FrameNodeStore.Key].Item;}
 static void AlterText(Xrecord record,string suffix){record.Values=record.Values.Concat(new[]{new TypedValue((int)DxfCode.Text,suffix)}).ToArray();}
 static void ChangeProject(Fixture f,double value){using(var tr=new Transaction(f.Db)){var before=ProjectStore.ReadProject(tr,f.Db);var p=FrameProjectParameters.FromDict(before.Payload);var next=p.defaults.Clone();next.geometry.cladding_front_offset_mm=value;f.Project=FrameProjectParameters.CreateNext(p,next);ProjectStore.WriteProject(tr,f.Db,before,f.Project.ToDict());tr.Commit();}}
 static void ChangeZone(Fixture f,double value){using(var tr=new Transaction(f.Db)){var before=ProjectStore.ReadZone(tr,f.Zone);var old=FrameZoneParameters.FromDict(before.Payload);var next=FrameZoneParameters.CreateNext(old,f.Project,new Dictionary<string,FrameParameterOverride>{{"geometry.cladding_front_offset_mm",FrameParameterOverride.Set(value)}});ProjectStore.WriteZone(tr,f.Zone,"geometry:original",before,next.ToDict());tr.Commit();}}
 static BlockReference Copy(Fixture f,BlockReference owner){var copy=f.Db.Add(new BlockReference(owner.Position,owner.BlockTableRecord));copy.CreateExtensionDictionary();((DBDictionary)copy.ExtensionDictionary.Item).SetAt(FrameNodeStore.Key,new Xrecord{Values=Record(owner).Values.ToArray(),XlateReferences=true});return copy;}
 public static int Main(string[] args){selected=FrameSolutionSelection.FromDict(Json.DeserializeObject(File.ReadAllText(args[0])));
  Check("actual node command cancellation at action selection entity form and point leaves drawing untouched",()=>{for(int stage=0;stage<4;stage++){var f=Fresh();var before=Dump(f);if(stage==0)f.Doc.Editor.Keywords.Clear();if(stage==1)f.Doc.Editor.Entity.Status=PromptStatus.Cancel;if(stage==2)Application.Dialog=o=>Forms.DialogResult.Cancel;if(stage==3)f.Doc.Editor.Point.Status=PromptStatus.Cancel;new FrameNodeCommand().Node();Need(Dump(f)==before&&Nodes(f).Count==0&&ProjectCadCounters.DataWrites==0,"cancel stage "+stage+" mutated database");}});
  Check("actual node command refuses unbound and unverified source without creating project defaults",()=>{var f=Fresh(false);var before=Dump(f);new FrameNodeCommand().Node();Need(Dump(f)==before&&Application.DialogCalls==0&&Nodes(f).Count==0,"unbound source silently migrated");f=Fresh();ZoneGeometryGuard.Zones[f.Zone.ObjectId].Ok=false;ZoneGeometryGuard.Zones[f.Zone.ObjectId].Reason="fixture invalid zone";before=Dump(f);new FrameNodeCommand().Node();Need(Dump(f)==before&&Application.DialogCalls==0,"invalid zone reached editor");});
  Check("actual node command creates one honest snapshot without changing project or binding",()=>{var f=Fresh();var sourceBefore=Resolve(f).Context.ToDict();new FrameNodeCommand().Node();Need(Nodes(f).Count==1,"create did not insert one node: "+f.Doc.Editor.Messages);var stored=Read(f,Nodes(f)[0]);Need(stored.Snapshot.Result.ClearanceStatus=="pass"&&stored.Snapshot.Result.GapMm==20,"actual core result lost");Need(Json.Serialize(sourceBefore)==Json.Serialize(Resolve(f).Context.ToDict()),"node changed project/binding");Need(ProjectCadCounters.ProjectRecordReads>=2&&ProjectCadCounters.ModelSpaceEnumerations==0,"bounded project reads violated");});
  Check("actual node command recomputes rejected input even if form returns OK",()=>{var f=Fresh();var before=Dump(f);Application.Dialog=o=>{((FrameNodeForm)o).Result=Input(169.999);return Forms.DialogResult.OK;};new FrameNodeCommand().Node();Need(Dump(f)==before&&Nodes(f).Count==0,"contradiction inserted despite core fail");});
  Check("actual renderer/store partial snapshot preserves permanent missing-check explanation",()=>{var f=Fresh();var owner=DirectCreate(f,FrameNodeGeometryInput.CreateDefault());var snapshot=Read(f,owner).Snapshot;Need(snapshot.Result.ClearanceStatus=="not_evaluated"&&snapshot.Result.Status=="partial","partial snapshot became pass");var text=string.Join("\n",((BlockTableRecord)owner.BlockTableRecord.Item).Children.Select(x=>x.Item).OfType<MText>().Select(x=>x.Contents).ToArray());Need(text.Contains("не выполнена")||text.Contains("не проверен")||text.Contains("не вычислен"),"partial CAD body lacks permanent warning: "+text);});
  Check("actual create fresh phase refuses project zone and geometry changes after point preview",()=>{for(int mode=0;mode<3;mode++){var f=Fresh();int local=mode;f.Doc.Editor.OnPoint=()=>{if(local==0)ChangeProject(f,240);if(local==1)ChangeZone(f,240);if(local==2)ZoneGeometryGuard.Zones[f.Zone.ObjectId].Fingerprint="geometry:changed";};new FrameNodeCommand().Node();Need(Nodes(f).Count==0,"stale mode "+mode+" created node");}});
  Check("actual create raw CAS refuses semantically equal project and zone rewrites",()=>{for(int mode=0;mode<2;mode++){var f=Fresh();int local=mode;f.Doc.Editor.OnPoint=()=>{Xrecord record;if(local==0){var nod=(DBDictionary)f.Db.NamedObjectsDictionaryId.Item;var root=(DBDictionary)nod.Items[ProjectStore.ProjectRootKey].Item;record=(Xrecord)root.Items[ProjectStore.ProjectRecordKey].Item;}else record=(Xrecord)((DBDictionary)f.Zone.ExtensionDictionary.Item).Items[ProjectStore.ZoneKey].Item;AlterText(record," ");};new FrameNodeCommand().Node();Need(Nodes(f).Count==0,"raw CAS failed mode "+mode);}});
  Check("actual create rolls back every persistent mutation boundary",()=>{var complete=Fresh();new FrameNodeCommand().Node();Need(Nodes(complete).Count==1,"baseline insert missing");int steps=ProjectCadCounters.Mutations;Need(steps>10,"no meaningful write boundaries measured");rollbackFailurePoints=steps;foreach(int step in Enumerable.Range(0,steps)){var f=Fresh();var before=Dump(f);ProjectCadCounters.FailAfterMutations=step;new FrameNodeCommand().Node();ProjectCadCounters.FailAfterMutations=-1;Need(Dump(f)==before&&Nodes(f).Count==0,"rollback left objects at write boundary "+step+"/"+steps);}});
  Check("actual node renderer store roundtrip validates actual CAD body and snapshot",()=>{var f=Fresh();var n=DirectCreate(f);var s=Read(f,n);Need(s.ZoneId==f.Zone.ObjectId&&s.OwnerId==n.ObjectId&&s.DefinitionId==n.BlockTableRecord,"identity lost");using(var tr=new Transaction(f.Db))Need(FrameNodeRenderer.CadContentDigest(tr,n)==s.CadContentDigest,"actual body hash mismatch");Need(s.Snapshot.Context.zone.owner_handle==f.Zone.Handle.ToString(),"zone provenance lost");});
  Check("actual node store refuses copied owner and damaged record without scanning drawing",()=>{var f=Fresh();var owner=DirectCreate(f);var copy=Copy(f,owner);Refuses(()=>Read(f,copy),"COPY accepted");Read(f,owner);AlterText(Record(owner),"broken");Refuses(()=>Read(f,owner),"malformed JSON accepted");Need(ProjectCadCounters.ModelSpaceEnumerations==0,"fallback scanned ModelSpace");});
  Check("actual node body digest detects line text and primitive-set tampering",()=>{for(int mode=0;mode<4;mode++){var f=Fresh();var n=DirectCreate(f);var b=(BlockTableRecord)n.BlockTableRecord.Item;if(mode==0){var line=b.Children.Select(x=>x.Item).OfType<Line>().First();line.EndPoint=new Point3d(line.EndPoint.X+1,line.EndPoint.Y,line.EndPoint.Z);}if(mode==1)b.Children.Select(x=>x.Item).OfType<MText>().First().Contents+=" changed";if(mode==2)b.Children.RemoveAt(0);if(mode==3)b.AppendEntity(new Circle{Center=new Point3d(0,0,0),Radius=1});Refuses(()=>Read(f,n),"body tamper mode "+mode+" accepted");}});
  Check("actual node transform keeps translation planar rotation but refuses physical scale mirror or tilt",()=>{var f=Fresh();var n=DirectCreate(f);n.Position=new Point3d(700,800,5);n.Rotation=Math.PI/3;Read(f,n);foreach(var scale in new[]{new Scale3d(2),new Scale3d(1,2,1),new Scale3d(-1,1,1),new Scale3d(1,1,-1)}){n.ScaleFactors=scale;Refuses(()=>Read(f,n),"scaled/mirrored node accepted");}n.ScaleFactors=new Scale3d(1);n.Normal=new Vector3d(0,1,0);Refuses(()=>Read(f,n),"tilted node accepted");});
  Check("actual node renderer refuses dynamic references attributes and foreign definition",()=>{var f=Fresh();var n=DirectCreate(f);n.IsDynamicBlock=true;Refuses(()=>Read(f,n),"dynamic block accepted");n.IsDynamicBlock=false;n.AttributeCollection.Add(f.Db.Add(new AttributeReference()).ObjectId);Refuses(()=>Read(f,n),"attribute overlay accepted");n.AttributeCollection.Clear();n.BlockTableRecord=f.Db.Add(new BlockTableRecord{Name="foreign"}).ObjectId;Refuses(()=>Read(f,n),"replacement definition accepted");});
  Check("actual node record distinguishes absent copied stale and damaged ownership",()=>{var f=Fresh();var unowned=f.Db.Add(new BlockReference(new Point3d(0,0,0),ObjectId.Null));RefusesCode(()=>Read(f,unowned),"E_NODE_NOT_OWNED");var owner=DirectCreate(f);RefusesCode(()=>Read(f,Copy(f,owner)),"E_NODE_COPY");f.Zone.IsErased=true;RefusesCode(()=>Read(f,owner),"E_NODE_SOURCE_STALE");f.Zone.IsErased=false;MutateRecord(owner,d=>d["renderer"]="unknown/99");Refuses(()=>Read(f,owner),"unknown renderer accepted");});
  Check("actual node record refuses reference substitution and invalid schema fields",()=>{for(int mode=0;mode<5;mode++){var f=Fresh();var n=DirectCreate(f);var record=Record(n);if(mode==0)record.Values=record.Values.Where(x=>x.TypeCode!=(int)DxfCode.SoftPointerId).ToArray();if(mode==1){var foreign=f.Db.Add(new Hatch());var refs=record.Values.Where(x=>x.TypeCode==(int)DxfCode.SoftPointerId).ToArray();refs[2].Value=foreign.ObjectId;}if(mode==2)MutateRecord(n,d=>d["extra"]=true);if(mode==3)MutateRecord(n,d=>d["drawing_units"]="4");if(mode==4)record.Values=new TypedValue[0];Refuses(()=>Read(f,n),"corruption mode "+mode+" accepted");}});
  Check("actual body verification detects text style borders and transparency changes",()=>{for(int mode=0;mode<5;mode++){var f=Fresh();var n=DirectCreate(f);var text=((BlockTableRecord)n.BlockTableRecord.Item).Children.Select(x=>x.Item).OfType<MText>().First();if(mode==0)text.ShowBorders=true;if(mode==1)text.Transparency=new Autodesk.AutoCAD.Colors.Transparency{Alpha=text.Transparency.Alpha,ByLayerFlag=true};if(mode==2)((TextStyleTableRecord)text.TextStyleId.Item).XScale=2;if(mode==3)text.ColumnCount=3;if(mode==4)text.BackgroundScaleFactor+=1;RefusesCode(()=>Read(f,n),"E_NODE_BODY_CHANGED");}});
  Check("actual own-body verification rejects clipping or unsupported extension dictionaries",()=>{var f=Fresh();var n=DirectCreate(f);((DBDictionary)n.ExtensionDictionary.Item).SetAt("ACAD_FILTER",new DBDictionary());Refuses(()=>Read(f,n),"unobserved clipping extension accepted");});
  Check("actual node command unit contract refuses non-mm and cancellation of unitless confirmation",()=>{var f=Fresh();f.Db.Insunits=UnitsValue.Inches;var before=Dump(f);new FrameNodeCommand().Node();Need(Dump(f)==before&&Nodes(f).Count==0,"inch DWG accepted");f=Fresh();f.Db.Insunits=UnitsValue.Undefined;before=Dump(f);new FrameNodeCommand().Node();Need(Dump(f)==before&&Nodes(f).Count==0,"unitless without confirmation accepted");});
  Check("actual unitless affirmative contract persists and later unit changes are not silent",()=>{var f=Fresh();f.Db.Insunits=UnitsValue.Undefined;f.Doc.Editor.Keywords.Enqueue(new PromptResult{Status=PromptStatus.OK,StringResult="Yes"});new FrameNodeCommand().Node();Need(Nodes(f).Count==1,"explicit unitless approval failed: "+f.Doc.Editor.Messages);var n=Nodes(f)[0];var stored=Read(f,n);Need(stored.DrawingUnits==UnitsValue.Undefined&&stored.UnitDeclaration=="unitless_explicit_mm","unitless intent not preserved");f.Db.Insunits=UnitsValue.Inches;SetCheck(f,n);var before=Dump(f);new FrameNodeCommand().Node();Need(Dump(f)==before,"unit mismatch check mutated drawing");});
  Check("actual node command converts UCS pick once and rejects UCS change during pick",()=>{var f=Fresh();f.Doc.Editor.CurrentUserCoordinateSystem=Matrix3d.Placement(new Point3d(100,200,0),new Scale3d(1),Math.PI/2);f.Doc.Editor.Point.Value=new Point3d(3,4,0);new FrameNodeCommand().Node();Need(Nodes(f).Count==1,"known UCS pick failed: "+f.Doc.Editor.Messages);var p=Nodes(f)[0].Position;Need(Math.Abs(p.X-96)<1e-9&&Math.Abs(p.Y-203)<1e-9,"UCS point not transformed exactly once");f=Fresh();var before=Dump(f);f.Doc.Editor.OnPoint=()=>f.Doc.Editor.CurrentUserCoordinateSystem=Matrix3d.Placement(new Point3d(1,2,0),new Scale3d(1),0);new FrameNodeCommand().Node();Need(Dump(f)==before&&Nodes(f).Count==0,"changed UCS accepted");});
  Check("actual node check is read-only both current and stale project",()=>{var f=Fresh();var n=DirectCreate(f);SetCheck(f,n);var before=Dump(f);ProjectCadCounters.Reset();new FrameNodeCommand().Node();Need(Dump(f)==before&&ProjectCadCounters.DataWrites==0,"check mutated snapshot");var current=f.Doc.Editor.Messages;Need(current.Length>0,"check gave no result");ChangeProject(f,240);SetCheck(f,n);before=Dump(f);ProjectCadCounters.Reset();new FrameNodeCommand().Node();Need(Dump(f)==before&&ProjectCadCounters.DataWrites==0,"stale check performed update");Need(f.Doc.Editor.Messages!=current,"stale check reported same result as current");});
  Check("actual create reads each source once per phase and verifies canonical geometry twice",()=>{var f=Fresh();ProjectCadCounters.Reset();ZoneGeometryGuard.Calls=0;new FrameNodeCommand().Node();Need(Nodes(f).Count==1,"create failed: "+f.Doc.Editor.Messages);Need(ProjectCadCounters.ProjectRecordReads==2&&ProjectCadCounters.ZoneRecordReads==2&&ZoneGeometryGuard.Calls==2,"source read/verification count is not one per phase");Need(ProjectCadCounters.ModelSpaceEnumerations==0,"create enumerated ModelSpace");});
  Check("actual check detects equal effective parameters with changed origin and removed binding",()=>{var f=Fresh();var n=DirectCreate(f);ChangeZone(f,230);SetCheck(f,n);new FrameNodeCommand().Node();Need(f.Doc.Editor.Messages.Contains("E_NODE_SOURCE_STALE"),"equal numbers concealed changed origin");using(var tr=new Transaction(f.Db)){ProjectStore.ClearZone(tr,f.Zone,"geometry:original",ProjectStore.ReadZone(tr,f.Zone));tr.Commit();}SetCheck(f,n);new FrameNodeCommand().Node();Need(f.Doc.Editor.Messages.Contains("E_NODE_UNBOUND"),"removed binding became local choice");});
  Check("actual body reader capacity and source record limits reject without truncation",()=>{var f=Fresh();var n=DirectCreate(f);var definition=(BlockTableRecord)n.BlockTableRecord.Item;while(definition.Children.Count<=FrameNodeRenderer.MaxPrimitives)definition.AppendEntity(new Line(new Point3d(0,0,0),new Point3d(1,1,0)));RefusesCode(()=>Read(f,n),"E_NODE_CAPACITY");f=Fresh();n=DirectCreate(f);AlterText(Record(n),new string(' ',1024*1024));RefusesCode(()=>Read(f,n),"E_NODE_CAPACITY");});
  Check("actual creation rejects late UCS units and deleted canonical owner before first write",()=>{for(int mode=0;mode<3;mode++){var f=Fresh();int local=mode;f.Doc.BeforeLock=()=>{if(local==0)f.Doc.Editor.CurrentUserCoordinateSystem=Matrix3d.Placement(new Point3d(100,0,0),new Scale3d(1),0);if(local==1)f.Db.Insunits=UnitsValue.Meters;if(local==2)f.Zone.IsErased=true;};new FrameNodeCommand().Node();Need(Nodes(f).Count==0&&ProjectCadCounters.DataWrites==0,"late environment mode "+mode+" wrote node");}});
  Check("actual node store requires explicit soft-reference translation contract",()=>{var f=Fresh();var n=DirectCreate(f);Need(Record(n).XlateReferences,"writer omitted reference translation contract");Record(n).XlateReferences=false;RefusesCode(()=>Read(f,n),"E_NODE_RECORD");});
  Check("actual node definition units origin and drawing capacity stay explicit",()=>{var f=Fresh();var n=DirectCreate(f);var definition=(BlockTableRecord)n.BlockTableRecord.Item;definition.Units=UnitsValue.Inches;RefusesCode(()=>Read(f,n),"E_NODE_DEFINITION");definition.Units=UnitsValue.Millimeters;definition.Origin=new Point3d(1,0,0);RefusesCode(()=>Read(f,n),"E_NODE_DEFINITION");var snapshot=Snapshot(f);RefusesCode(()=>FrameNodeDrawingBuilder.Build(snapshot.Result,Enumerable.Repeat("fixture capacity",4097)),"E_NODE_CAPACITY");});
  Check("actual create isolates current text style and preserves blocked destination layer",()=>{var f=Fresh();var current=(TextStyleTableRecord)f.Db.Textstyle.Item;current.XScale=5;current.IsVertical=true;current.TextSize=40;new FrameNodeCommand().Node();Need(Nodes(f).Count==1,"current style prevented controlled rendering");var body=(BlockTableRecord)Nodes(f)[0].BlockTableRecord.Item;foreach(var text in body.Children.Select(x=>x.Item).OfType<MText>()){var own=(TextStyleTableRecord)text.TextStyleId.Item;Need(text.TextStyleId!=f.Db.Textstyle&&own.XScale==1&&!own.IsVertical&&own.TextSize==0,"user style leaked into node");}Need(current.XScale==5&&current.IsVertical&&current.TextSize==40,"node modified user's style");f=Fresh();var table=(LayerTable)f.Db.LayerTableId.Item;table.Add(new LayerTableRecord{Name=FrameNodeRenderer.LayerName,IsLocked=true,Color=Autodesk.AutoCAD.Colors.Color.FromColorIndex(Autodesk.AutoCAD.Colors.ColorMethod.ByAci,7)});var before=Dump(f);new FrameNodeCommand().Node();Need(Dump(f)==before&&Nodes(f).Count==0&&f.Doc.Editor.Messages.Contains("E_NODE_LAYER"),"locked layer was silently changed");});
  Check("actual read-only check distinguishes deleted zone and explicit new generation",()=>{var f=Fresh();var n=DirectCreate(f);f.Zone.IsErased=true;SetCheck(f,n);new FrameNodeCommand().Node();Need(f.Doc.Editor.Messages.Contains("E_NODE_SOURCE_STALE"),"deleted zone not stale");f.Zone.IsErased=false;ZoneGeometryGuard.Zones[f.Zone.ObjectId].Fingerprint="geometry:rebound";using(var tr=new Transaction(f.Db)){ProjectStore.WriteZone(tr,f.Zone,"geometry:rebound",ProjectStore.ReadZone(tr,f.Zone),f.Binding.ToDict());tr.Commit();}SetCheck(f,n);var before=Dump(f);new FrameNodeCommand().Node();Need(Dump(f)==before&&f.Doc.Editor.Messages.Contains("E_NODE_SOURCE_STALE"),"new generation silently adopted");});
  Check("actual renderer and stored snapshot preserve nextUp479.82 cladding coordinate bit for bit",()=>{const long expected=4647148698899442566L;var f=Fresh();var choice=FrameNodeGeometry.CloneSelection(f.Project.defaults);choice.geometry.cladding_front_offset_mm=BitConverter.Int64BitsToDouble(expected);var snapshot=ExactSnapshot(f,choice,Input());var node=CreateSnapshot(f,snapshot);var saved=Read(f,node).Snapshot;Need(Bits(saved.Selection.geometry.cladding_front_offset_mm.Value)==expected,"snapshot changed original cladding input");Need(Bits(saved.Result.CladdingFrontXMm.Value)==expected,"result changed cladding coordinate by one ULP");Need(Bits(saved.Result.Planes.Single(x=>x.Id=="cladding_front").XMm)==expected,"exported cladding plane drifted");var dimension=saved.Result.Dimensions.Single(x=>x.Id=="cladding_offset");Need(Bits(dimension.ToXMm)==expected&&Bits(dimension.ValueMm)==expected,"dimension endpoints/value drifted");var definition=(BlockTableRecord)node.BlockTableRecord.Item;Need(definition.Children.Select(x=>x.Item).OfType<Line>().Any(x=>Bits(x.StartPoint.X)==expected&&Bits(x.EndPoint.X)==expected),"actual CAD plane did not preserve declared coordinate");Need(definition.Children.Select(x=>x.Item).OfType<MText>().Any(x=>x.Contents.Contains(dimension.ValueText)),"exact dimension label absent from CAD");});
  Check("actual renderer and stored tiny layer-only partial preserve 1e-28 bit for bit",()=>{const long expected=4188260752279232537L;var f=Fresh();var choice=FrameNodeGeometry.CloneSelection(f.Project.defaults);choice.geometry.cladding_front_offset_mm=null;choice.geometry.insulation_layers_mm=new List<double>{BitConverter.Int64BitsToDouble(expected)};var snapshot=ExactSnapshot(f,choice,FrameNodeGeometryInput.CreateDefault());var node=CreateSnapshot(f,snapshot);var saved=Read(f,node).Snapshot;Need(saved.Result.Status=="partial"&&saved.Result.ClearanceStatus=="not_evaluated","tiny layer partial was rejected or promoted to pass");Need(Bits(saved.Result.InsulationOuterXMm.Value)==expected&&Bits(saved.Result.Layers[0].EndXMm)==expected&&Bits(saved.Result.Layers[0].ThicknessMm)==expected,"tiny summary/layer drifted");Need(Bits(saved.Result.Planes.Single(x=>x.Id=="insulation_1").XMm)==expected,"tiny exported plane drifted");var dimension=saved.Result.Dimensions.Single(x=>x.Id=="layer_1");Need(Bits(dimension.ToXMm)==expected&&Bits(dimension.ValueMm)==expected,"tiny dimension drifted");Need(((BlockTableRecord)node.BlockTableRecord.Item).Children.Select(x=>x.Item).OfType<Line>().Any(x=>Bits(x.StartPoint.X)==expected&&Bits(x.EndPoint.X)==expected),"actual CAD tiny layer lost its coordinate");});
  Check("actual command refuses legacy source drift before UI and permits only exact numeric declarations",()=>{foreach(bool tiny in new[]{false,true}){long expected=tiny?4188260752279232537L:4647148698899442566L;var f=Fresh();var changes=new Dictionary<string,FrameParameterOverride>();if(tiny){changes.Add("geometry.cladding_front_offset_mm",FrameParameterOverride.Clear());changes.Add("geometry.insulation_layers_mm",FrameParameterOverride.Set(new[]{BitConverter.Int64BitsToDouble(expected)}));Application.Dialog=o=>{((FrameNodeForm)o).Result=FrameNodeGeometryInput.CreateDefault();return Forms.DialogResult.OK;};}else changes.Add("geometry.cladding_front_offset_mm",FrameParameterOverride.Set(BitConverter.Int64BitsToDouble(expected)));var zone=FrameZoneParameters.CreateNext(f.Binding,f.Project,changes);using(var tr=new Transaction(f.Db)){ProjectStore.WriteZone(tr,f.Zone,"geometry:original",ProjectStore.ReadZone(tr,f.Zone),zone.ToDict());tr.Commit();}var resolved=Resolve(f).Selection;long actual=Bits(tiny?resolved.geometry.insulation_layers_mm[0]:resolved.geometry.cladding_front_offset_mm.Value);var before=Dump(f);ProjectCadCounters.Reset();new FrameNodeCommand().Node();if(actual!=expected){Need(Nodes(f).Count==0&&Application.DialogCalls==0&&Dump(f)==before&&ProjectCadCounters.DataWrites==0&&f.Doc.Editor.Messages.Contains("E_NODE_SOURCE_PRECISION"),"legacy drift did not precisely refuse before UI/write: "+f.Doc.Editor.Messages);}else{Need(Nodes(f).Count==1,"exact source refused: "+f.Doc.Editor.Messages);var node=Nodes(f)[0];var value=Read(f,node).Snapshot.Result;Need(Bits(tiny?value.InsulationOuterXMm.Value:value.CladdingFrontXMm.Value)==expected,"accepted command rounded its exact source");SetCheck(f,node);new FrameNodeCommand().Node();Need(f.Doc.Editor.Messages.Contains("Снимок и тело схемы соответствуют текущим источникам"),"exact accepted command snapshot failed check: "+f.Doc.Editor.Messages);}}});
  Check("actual node CAD work stays bounded with unrelated ModelSpace and repeated checks",()=>{var f=Fresh();var node=DirectCreate(f);var space=(BlockTableRecord)f.Db.CurrentSpaceId.Item;for(int i=0;i<10000;i++)space.AppendEntity(new Circle{Center=new Point3d(i,i,0),Radius=1});SetCheck(f,node);ProjectCadCounters.Reset();new FrameNodeCommand().Node();Need(ProjectCadCounters.ModelSpaceEnumerations==0&&ProjectCadCounters.ProjectRecordReads==1&&ProjectCadCounters.ZoneRecordReads==1,"check searched drawing or reread parameter records");long oneReads=ProjectCadCounters.ObjectReads;int oneVisits=ProjectCadCounters.PrimitiveVisits;Need(oneReads<1000&&oneVisits>0,"check work not bounded by own body");foreach(int count in new[]{1,100,1000}){var sample=Fresh();var own=DirectCreate(sample);ProjectCadCounters.Reset();var watch=System.Diagnostics.Stopwatch.StartNew();for(int i=0;i<count;i++){SetCheck(sample,own);new FrameNodeCommand().Node();}watch.Stop();Need(ProjectCadCounters.ProjectRecordReads==count&&ProjectCadCounters.ZoneRecordReads==count&&ProjectCadCounters.ModelSpaceEnumerations==0,"cross-operation read counts changed");Need(ProjectCadCounters.PrimitiveVisits==oneVisits*count&&ProjectCadCounters.ObjectReads==oneReads*count,"CAD work grew beyond each own body");Performance.Add(new{operations=count,object_reads=ProjectCadCounters.ObjectReads,primitive_visits=ProjectCadCounters.PrimitiveVisits,project_reads=ProjectCadCounters.ProjectRecordReads,zone_reads=ProjectCadCounters.ZoneRecordReads,elapsed_ms=watch.Elapsed.TotalMilliseconds,claim="synthetic only; no native host time"});}});
  foreach(string name in new[]{"pass","partial","eight_layers"}){var f=Fresh();FrameNodeGeometryInput local=name=="partial"?FrameNodeGeometryInput.CreateDefault():Input();if(name=="eight_layers"){var choice=f.Project.defaults.Clone();choice.geometry.insulation_layers_mm=new List<double>{25,25,25,25,25,25,25,25};choice.geometry.cladding_front_offset_mm=300;using(var tr=new Transaction(f.Db)){var previous=ProjectStore.ReadProject(tr,f.Db);f.Project=FrameProjectParameters.CreateNext(f.Project,choice);ProjectStore.WriteProject(tr,f.Db,previous,f.Project.ToDict());tr.Commit();}local=Input(220);}var snapshot=Snapshot(f,local);var drawing=FrameNodeDrawingBuilder.Build(snapshot.Result,snapshot.CaptionLines());File.WriteAllText(Path.Combine(Path.GetDirectoryName(args[1]),"drawing_"+name+".json"),Json.Serialize(new{snapshot=snapshot.ToDict(),result=snapshot.Result.ToDict(),drawing=drawing.ToDict()}));}
  var report=new{status=failed==0?"PASS":"FAIL",checks=Cases.Count,failed,cases=Cases,performance=Performance,rollback_failure_points=rollbackFailurePoints,live_autocad_checked=false,scope="Actual node command/store/renderer/drawing/core with prompt and canonical-zone verification seams and explicit CAD in-memory model; no native COPY/Undo/UCS/Save guarantee"};File.WriteAllText(args[1],Json.Serialize(report));Console.WriteLine("Node CAD: "+Cases.Count+" checks, "+failed+" failures");return failed==0?0:1;
 }
}
