; Universal native authoring runtime. Input afn:data is supplied by generate.py.
; Requires full Windows AutoCAD 2024, Unicode AutoLISP (LISPSYS 1 or 2).
; This source has not been executed in an AutoCAD host in the Linux check.
(vl-load-com)

(defun afn:get (key data) (cdr (assoc key data)))
(defun afn:pt (p) (list (car p) (cadr p) 0.0))
(defun afn:fail (message)
  (setq afn:failure message)
  (exit))
(defun afn:assert (ok message) (if (not ok) (afn:fail message)))
(defun afn:unbox (x)
  (cond ((= (type x) 'VARIANT) (afn:unbox (vlax-variant-value x)))
        ((= (type x) 'SAFEARRAY) (mapcar 'afn:unbox (vlax-safearray->list x)))
        (T x)))
(defun afn:cmd (arguments)
  (apply 'vl-cmdf arguments)
  ; An unexpected extra prompt is a failure, not permission to feed the next command.
  (afn:assert (= 0 (logand 3 (getvar "CMDACTIVE")))
    (strcat "Command did not finish: " (car arguments))))
(defun afn:open-editor (name)
  ; afn:editor-owned is deliberately dynamically bound by ATFNATIVEBUILD.
  ; Its preflight proved that no foreign Block Editor was open.
  (vl-cmdf "_.-BEDIT" name)
  (if (= (getvar "BLOCKEDITOR") 1) (setq afn:editor-owned T))
  (afn:assert (and afn:editor-owned (= 0 (logand 3 (getvar "CMDACTIVE")))) "BEDIT did not open cleanly"))
(defun afn:close-editor ()
  (afn:cmd '("_.BSAVE"))
  (afn:cmd '("_.BCLOSE"))
  (afn:assert (= (getvar "BLOCKEDITOR") 0) "Our Block Editor did not close")
  (setq afn:editor-owned nil))
(defun afn:sort (values)
  ; vl-sort removes duplicates; sort indices to preserve repeated geometry.
  (mapcar '(lambda (i) (nth i values))
    (vl-sort-i values '(lambda (a b) (< (vl-prin1-to-string a) (vl-prin1-to-string b))))))
(defun afn:property (reference name / found prop)
  (foreach prop (vlax-invoke reference 'GetDynamicBlockProperties)
    (if (= (vla-get-PropertyName prop) name)
      (progn (afn:assert (null found) (strcat "Duplicate property: " name)) (setq found prop))))
  (afn:assert found (strcat "Missing native property: " name))
  found)
(defun afn:value (reference name)
  (afn:unbox (vla-get-Value (afn:property reference name))))
(defun afn:set (reference name value / prop old)
  (setq prop (afn:property reference name) old (vla-get-Value prop))
  (afn:assert (= :vlax-false (vla-get-ReadOnly prop)) (strcat "Read-only property: " name))
  (vla-put-Value prop (vlax-make-variant value (vlax-variant-type old)))
  (vla-Update reference)
  ; ActiveX can silently ignore an out-of-range assignment. Always read it back.
  (afn:assert (equal value (afn:value reference name) 1e-7) (strcat "Native setter rejected: " name)))
(defun afn:apply (reference state / entry)
  ; Discrete state first. Recheck the final property tuple after every action
  ; has evaluated, so a later property cannot silently invalidate an earlier one.
  (afn:set reference "AFN_VARIANT" (afn:get "AFN_VARIANT" state))
  (afn:set reference "AFN_INSULATION" (afn:get "AFN_INSULATION" state))
  (afn:set reference "AFN_CLADDING_X" (afn:get "AFN_CLADDING_X" state))
  (foreach entry state
    (afn:assert (equal (cdr entry) (afn:value reference (car entry)) 1e-7)
      (strcat "Final native property tuple mismatch: " (car entry)))))
(defun afn:insert (space name position scale rotation)
  (vla-InsertBlock space (vlax-3d-point position) name scale scale scale rotation))
(defun afn:signature (reference / properties prop values name)
  (afn:assert (= :vlax-true (vla-get-IsDynamicBlock reference)) "Definition is not a native dynamic block")
  (setq properties (vlax-invoke reference 'GetDynamicBlockProperties))
  (afn:assert (= (length properties) 3) "Expected exactly three native dynamic properties")
  (foreach name '("AFN_INSULATION" "AFN_CLADDING_X")
    (setq prop (afn:property reference name))
    (afn:assert (and (= :vlax-false (vla-get-ReadOnly prop)) (numberp (afn:value reference name)))
      (strcat "Writable numeric property required: " name)))
  (setq prop (afn:property reference "AFN_VARIANT") values (afn:unbox (vla-get-AllowedValues prop)))
  (afn:assert (= :vlax-false (vla-get-ReadOnly prop)) "Visibility property is read-only")
  (afn:assert (equal (afn:sort values) (afn:sort (afn:get "variants" afn:data)))
    "Visibility allowed values do not match the two variants"))

(defun afn:make (entry / kind common data entity point obj tag)
  (setq kind (afn:get "type" entry)
    common (list '(8 . "0") (cons 62 (cond ((afn:get "color" entry)) (T 256)))))
  (cond
    ((= kind "line")
      (setq data (append '((0 . "LINE")) common
        (list (cons 10 (afn:pt (afn:get "start" entry))) (cons 11 (afn:pt (afn:get "end" entry)))))))
    ((= kind "polyline")
      (setq data (append '((0 . "LWPOLYLINE") (100 . "AcDbEntity")) common
        (list '(100 . "AcDbPolyline") (cons 90 (length (afn:get "points" entry)))
          (cons 70 (if (afn:get "closed" entry) 1 0)))))
      (foreach point (afn:get "points" entry) (setq data (append data (list (cons 10 point))))))
    ((= kind "circle")
      (setq data (append '((0 . "CIRCLE")) common
        (list (cons 10 (afn:pt (afn:get "center" entry))) (cons 40 (afn:get "radius" entry))))))
    ((= kind "text")
      (setq data (append '((0 . "TEXT")) common
        (list (cons 10 (afn:pt (afn:get "position" entry))) (cons 40 (afn:get "height" entry))
          (cons 1 (afn:get "text" entry)) '(7 . "Standard") '(50 . 0.0)))))
    ((= kind "attribute")
      (setq tag (afn:get "tag" entry)
        data (append '((0 . "ATTDEF") (100 . "AcDbEntity")) common
          (list '(100 . "AcDbText") (cons 10 (afn:pt (afn:get "position" entry)))
            (cons 40 (afn:get "height" entry)) (cons 1 (afn:get "text" entry))
            '(7 . "Standard") '(50 . 0.0) '(100 . "AcDbAttributeDefinition")
            '(280 . 0) (cons 3 (cond ((afn:get "prompt" entry)) (T tag)))
            (cons 2 tag) '(70 . 0) '(73 . 0) '(74 . 0) '(280 . 1)))))
    ((= kind "dimension")
      (afn:cmd (list "_.DIMALIGNED" "_non" (afn:pt (afn:get "p1" entry))
        "_non" (afn:pt (afn:get "p2" entry)) "_non" (afn:pt (afn:get "line_point" entry))))
      (setq entity (entlast) obj (vlax-ename->vla-object entity))
      (afn:assert (= (vla-get-ObjectName obj) "AcDbAlignedDimension") "DIMALIGNED did not create a dimension")
      ; A template's DIMLFAC / DIMPOST must not relabel millimetres silently.
      (vla-put-LinearScaleFactor obj 1.0)
      (vla-put-ScaleFactor obj 1.0)
      (vla-put-TextOverride obj "")
      (vla-put-TextPrefix obj "")
      (vla-put-TextSuffix obj "")
      (vla-put-AltUnits obj :vlax-false)
      (vla-put-UnitsFormat obj 2)
      (vla-put-PrimaryUnitsPrecision obj 2)
      (vla-put-SuppressTrailingZeros obj :vlax-true)
      (vla-put-TextHeight obj (cond ((afn:get "height" entry)) (T 3.0)))
      (vla-put-ArrowheadSize obj (cond ((afn:get "height" entry)) (T 3.0)))
      (vla-put-Color obj (cond ((afn:get "color" entry)) (T 256)))))
  (if data (progn (afn:assert (entmake data) (strcat "Cannot create: " (afn:get "id" entry))) (setq entity (entlast))))
  (afn:assert entity "Entity construction returned no object")
  entity)
(defun afn:set-of (ids entities / result ident object)
  (setq result (ssadd))
  (foreach ident ids
    (setq object (cdr (assoc ident entities)))
    (afn:assert (and object (entget object)) (strcat "Missing authoring entity: " ident))
    (ssadd object result))
  result)
(defun afn:build-definition (name space / old-state reference entities entry parameters name-p spec ename action frame selected variants variant ids)
  ; Begin with an empty, exclusively owned definition. Never redefine an existing name.
  (afn:assert (entmake (list '(0 . "BLOCK") (cons 2 name) '(70 . 0) '(10 0.0 0.0 0.0))) "Cannot create block header")
  (afn:assert (entmake '((0 . "ENDBLK"))) "Cannot close block header")
  (afn:open-editor name)
  (afn:cmd (list "_.BPARAMETER" "_Visibility" "_Name" "AFN_VARIANT" "_Label" "AFN_VARIANT" '(0.0 -100.0 0.0)))
  (afn:close-editor)
  ; Read the localized default state through the native reference API.
  ; No hard-coded English/Russian VisibilityState0 name and no private DXF internals.
  (setq reference (afn:insert space name '(0.0 0.0 0.0) 1.0 0.0))
  (afn:assert (= :vlax-true (vla-get-IsDynamicBlock reference)) "Visibility parameter was not created")
  (setq old-state (afn:value reference "AFN_VARIANT"))
  (vla-Delete reference)
  (afn:open-editor name)
  (foreach entry (afn:get "entities" afn:data)
    (setq entities (cons (cons (afn:get "id" entry) (afn:make entry)) entities)))
  (foreach entry (afn:get "parameters" afn:data)
    (setq name-p (car entry) spec (cdr entry))
    (afn:cmd (list "_.BPARAMETER" "_Linear" "_Name" name-p "_Label" name-p
      "_Base" "_Startpoint" "_Palette" "_Yes"
      (afn:pt (afn:get "start" spec)) (afn:pt (afn:get "end" spec)) (afn:pt (afn:get "label" spec)) 1))
    (setq parameters (cons (cons name-p (entlast)) parameters)))
  (foreach action (afn:get "actions" afn:data)
    (setq name-p (afn:get "parameter" action) ename (cdr (assoc name-p parameters))
      spec (afn:get name-p (afn:get "parameters" afn:data))
      selected (afn:set-of (afn:get "entities" action) entities))
    (if (= (afn:get "kind" action) "stretch")
      (progn
        (setq frame (afn:get "frame" action))
        (afn:cmd (list "_.BACTIONTOOL" "_Stretch" (list ename (afn:pt (afn:get "label" spec)))
          (afn:pt (afn:get "end" spec)) (afn:pt (car frame)) (afn:pt (cadr frame)) selected "")))
      (afn:cmd (list "_.BACTIONTOOL" "_Move" (list ename (afn:pt (afn:get "label" spec)))
        (afn:pt (afn:get "end" spec)) selected ""))))
  (setq variants (afn:get "variants" afn:data))
  (foreach variant variants
    (afn:cmd (list "_.-BVSTATE" "_New" variant "_Hide"))
    (setq ids nil)
    (foreach entry (afn:get "entities" afn:data)
      (if (or (null (afn:get "variant" entry)) (= (afn:get "variant" entry) variant))
        (setq ids (cons (afn:get "id" entry) ids))))
    (afn:cmd (list "_.BVSHOW" (afn:set-of ids entities) "" "_Current")))
  (afn:cmd (list "_.-BVSTATE" "_Set" (car variants)))
  (afn:assert (not (member old-state variants)) "Unexpected collision with native default visibility state")
  (afn:cmd (list "_.-BVSTATE" "_Delete" old-state))
  (afn:close-editor))

(defun afn:read-properties (object names / result key)
  (foreach key names
    (afn:assert (vlax-property-available-p object key) (strcat "Unsupported native snapshot property: " (vl-symbol-name key)))
    (setq result (cons (afn:unbox (vlax-get-property object key)) result)))
  (reverse result))
(defun afn:entity-snapshot (object / kind fields)
  (setq kind (vla-get-ObjectName object))
  (setq fields
    (cond ((= kind "AcDbLine") '(StartPoint EndPoint))
          ((= kind "AcDbPolyline") '(Coordinates Closed Elevation))
          ((= kind "AcDbCircle") '(Center Radius))
          ((= kind "AcDbText") '(InsertionPoint TextString Height Rotation))
          ((= kind "AcDbAttributeDefinition") '(InsertionPoint TagString TextString Height Rotation))
          ((= kind "AcDbAlignedDimension") '(ExtLine1Point ExtLine2Point Measurement TextPosition TextOverride LinearScaleFactor TextPrefix TextSuffix UnitsFormat))
          (T (afn:fail (strcat "Unsupported native exploded object: " kind)))))
  (cons kind (afn:read-properties object fields)))
(defun afn:attributes (reference / result object)
  (if (= :vlax-true (vla-get-HasAttributes reference))
    (foreach object (vlax-invoke reference 'GetAttributes)
      (setq result (cons (afn:read-properties object '(TagString TextString InsertionPoint Height Rotation)) result))))
  (afn:sort result))
(defun afn:snapshot (reference / geometry object exploded props name)
  ; Explode returns temporary, native-evaluated geometry. Delete every temporary
  ; object; the original reference, its dynamic definition and siblings are unchanged.
  (setq exploded (vlax-invoke reference 'Explode))
  (foreach object exploded (setq geometry (cons (afn:entity-snapshot object) geometry)) (vla-Delete object))
  (foreach name '("AFN_INSULATION" "AFN_CLADDING_X" "AFN_VARIANT")
    (setq props (cons (cons name (afn:value reference name)) props)))
  (list (afn:sort geometry) (reverse props) (afn:attributes reference)
    (afn:read-properties reference '(InsertionPoint XScaleFactor YScaleFactor ZScaleFactor Rotation))))
(defun afn:geometry-only (snapshot / result entity)
  (foreach entity (car snapshot)
    (if (member (car entity) '("AcDbLine" "AcDbPolyline" "AcDbCircle")) (setq result (cons entity result))))
  result)
(defun afn:dimensions-only (snapshot / result entity)
  (foreach entity (car snapshot)
    (if (= (car entity) "AcDbAlignedDimension") (setq result (cons entity result))))
  result)
(defun afn:marks-only (snapshot / result entity)
  (foreach entity (car snapshot)
    (if (= (car entity) "AcDbText") (setq result (cons entity result))))
  result)
(defun afn:probe-one (reference / before after defaults alternate name)
  (setq defaults (afn:get "defaults" afn:data) alternate (afn:get "alternate" afn:data))
  (afn:apply reference defaults)
  (setq before (afn:snapshot reference))
  (foreach name '("AFN_INSULATION" "AFN_CLADDING_X" "AFN_VARIANT")
    (afn:set reference name (afn:get name alternate))
    (setq after (afn:snapshot reference))
    (afn:assert (not (equal (afn:geometry-only before) (afn:geometry-only after) 1e-7))
      (strcat "Property changed but native geometry did not: " name))
    (if (= name "AFN_VARIANT")
      (afn:assert (not (equal (afn:marks-only before) (afn:marks-only after) 1e-7)) "Visibility did not change the native marks")
      (afn:assert (not (equal (afn:dimensions-only before) (afn:dimensions-only after) 1e-7))
        (strcat "Native dimension did not change: " name)))
    (afn:set reference name (afn:get name defaults))
    (afn:assert (equal before (afn:snapshot reference) 1e-7) (strcat "Roundtrip drift: " name))))
(defun afn:five (space name / refs reference index positions scales rotations before after copy snapshot)
  (setq positions '((0.0 0.0 0.0) (1200.0 0.0 0.0) (2400.0 0.0 0.0) (3600.0 0.0 0.0) (4800.0 0.0 0.0))
    scales '(1.0 1.0 2.0 1.0 1.0) rotations (list 0.0 (/ pi 2.0) (/ pi 6.0) 0.0 pi) index 0)
  (repeat 5
    (setq reference (afn:insert space name (nth index positions) (nth index scales) (nth index rotations)))
    (afn:signature reference)
    (afn:apply reference (afn:get "defaults" afn:data))
    (setq refs (append refs (list reference)) index (1+ index)))
  (afn:probe-one (car refs))
  (setq before (mapcar 'afn:snapshot refs) index 0)
  (foreach reference refs
    (if (< index 3) (afn:apply reference (afn:get "alternate" afn:data)))
    (setq index (1+ index)))
  (setq after (mapcar 'afn:snapshot refs) index 0)
  (repeat 5
    (if (< index 3)
      (progn
        (afn:assert (not (equal (car (nth index before)) (car (nth index after)) 1e-7)) "Selected instance geometry did not change")
        (afn:assert (equal (cddr (nth index before)) (cddr (nth index after)) 1e-7) "Attribute or insertion transform changed"))
      (afn:assert (equal (nth index before) (nth index after) 1e-7) "Unselected instance changed"))
    (setq index (1+ index)))
  ; Repeat B, return to A, and return to B. No accumulated shifts.
  (foreach reference (list (nth 0 refs) (nth 1 refs) (nth 2 refs))
    (afn:apply reference (afn:get "alternate" afn:data)))
  (afn:assert (equal after (mapcar 'afn:snapshot refs) 1e-7) "Repeated assignment drift")
  (foreach reference refs (afn:apply reference (afn:get "defaults" afn:data)))
  (afn:assert (equal before (mapcar 'afn:snapshot refs) 1e-7) "Five-instance reverse transition drift")
  (foreach reference (list (nth 0 refs) (nth 1 refs) (nth 2 refs))
    (afn:apply reference (afn:get "alternate" afn:data)))
  (afn:assert (equal after (mapcar 'afn:snapshot refs) 1e-7) "Five-instance second transition drift")
  ; Native database Copy is tested here; the UI COPY/UNDO and save/open are a separate host check.
  (setq reference (car refs) snapshot (afn:snapshot reference) copy (vla-Copy reference))
  (afn:assert (equal snapshot (afn:snapshot copy) 1e-7) "Native copied block differs")
  (afn:apply copy (afn:get "defaults" afn:data))
  (afn:assert (equal snapshot (afn:snapshot reference) 1e-7) "Copy modification affected original")
  (vla-Delete copy)
  refs)
(defun afn:marker (document name / block dictionary record values entity readback)
  (setq block (vla-Item (vla-get-Blocks document) name)
    dictionary (vlax-vla-object->ename (vla-GetExtensionDictionary block)))
  (afn:assert (null (dictsearch dictionary "AF_NODE_LIBRARY")) "Definition marker already exists")
  (setq values (append
    (list (cons 1 (afn:get "node_id" afn:data)) (cons 90 (afn:get "version" afn:data)))
    (mapcar '(lambda (v) (cons 1 v))
      (append '("AFN_INSULATION" "AFN_CLADDING_X" "AFN_VARIANT") (afn:get "variants" afn:data)))))
  (setq entity (entmakex (append '((0 . "XRECORD") (100 . "AcDbXrecord") (280 . 1)) values)))
  (afn:assert entity "Cannot create native definition marker")
  (afn:assert (dictadd dictionary "AF_NODE_LIBRARY" entity) "Cannot attach native definition marker")
  (setq readback (vl-remove-if-not '(lambda (x) (member (car x) '(1 90))) (entget entity)))
  (afn:assert (equal values readback) "Native marker readback mismatch"))
(defun afn:restore (settings / entry)
  (foreach entry settings (vl-catch-all-apply 'setvar (list (car entry) (cdr entry)))))

(defun c:ATFNATIVEBUILD (/ *error* document space name output settings undo-state commands-owned afn:editor-owned refs setting)
  (setq afn:failure nil undo-state nil commands-owned nil afn:editor-owned nil)
  (defun *error* (message / result)
    ; No work in an existing drawing is allowed by the preflight below. Close our
    ; editor without saving, end our own group, and roll back only that group.
    (if commands-owned
      (repeat 3 (if (/= 0 (logand 3 (getvar "CMDACTIVE"))) (command))))
    (if (and afn:editor-owned (= (getvar "BLOCKEDITOR") 1))
      (vl-catch-all-apply 'command-s '("_.BCLOSE" "_Discard")))
    (if (and (equal undo-state "open") (= (getvar "BLOCKEDITOR") 0))
      (progn
        (setq result (vl-catch-all-apply 'command-s '("_.UNDO" "_End")))
        (if (not (vl-catch-all-error-p result)) (setq undo-state "ended"))))
    (if (and (equal undo-state "ended") (= (getvar "BLOCKEDITOR") 0))
      (vl-catch-all-apply 'command-s '("_.U")))
    (if commands-owned (afn:restore settings))
    (princ (strcat "\nAFN BUILD ABORTED: " (if afn:failure afn:failure message)))
    (princ "\nThe library was not confirmed saved. Do not use an incomplete output. If rollback was interrupted, close this new drawing without saving.")
    (princ))
  (afn:assert afn:data "Load a generated authoring LISP, not the runtime alone")
  (afn:assert (= 0 (getvar "BLOCKEDITOR")) "Close Block Editor before starting")
  (afn:assert (member (getvar "LISPSYS") '(1 2)) "Unicode AutoLISP required: LISPSYS 1, then restart AutoCAD")
  (afn:assert (and (= 0 (getvar "DWGTITLED")) (= 0 (getvar "DBMOD")) (= 1 (getvar "TILEMODE")))
    "Run only in a NEW, clean, unsaved model drawing")
  (setq document (vla-get-ActiveDocument (vlax-get-acad-object)) space (vla-get-ModelSpace document)
    name (afn:get "block_name" afn:data))
  (afn:assert (= 0 (vla-get-Count space)) "Model space must be empty")
  (afn:assert (null (tblsearch "BLOCK" name)) "Refusing to redefine an existing block")
  (setq output (getfiled "Save NEW private native library DWG" (strcat name ".dwg") "dwg" 1))
  (afn:assert output "Cancelled before drawing changes")
  (afn:assert (null (findfile output)) "Refusing to overwrite an existing DWG")
  (foreach setting '("CMDECHO" "OSMODE" "SNAPMODE" "BACTIONBARMODE" "DYNMODE" "DIMASSOC" "ATTREQ" "ATTDIA" "INSUNITS")
    (setq settings (cons (cons setting (getvar setting)) settings)))
  (setq commands-owned T)
  (afn:cmd '("_.UNDO" "_Begin"))
  (setq undo-state "open")
  (foreach setting '(("CMDECHO" . 0) ("OSMODE" . 0) ("SNAPMODE" . 0) ("BACTIONBARMODE" . 1)
      ("DYNMODE" . 0) ("DIMASSOC" . 1) ("ATTREQ" . 0) ("ATTDIA" . 0) ("INSUNITS" . 4))
    (setvar (car setting) (cdr setting)))
  (afn:build-definition name space)
  (setq refs (afn:five space name))
  ; Compatibility is stamped only after native dynamic evaluation passed.
  (afn:marker document name)
  (afn:restore settings)
  (setvar "INSUNITS" 4)
  (vla-Regen document 1)
  (afn:cmd '("_.ZOOM" "_Extents"))
  (afn:cmd '("_.UNDO" "_End"))
  (setq undo-state "ended")
  (vla-SaveAs document output)
  (setq undo-state nil commands-owned nil)
  (princ (strcat "\nSaved native library: " output))
  (princ "\nPASS IN THIS HOST: native signature/actions/dimensions/marks, five instances (3 changed/2 unchanged), A-B-A-B, repeat, database Copy.")
  (princ "\nSTILL REQUIRED: manual grips/Properties, plugin selection command and cancel/Undo, UI COPY, save-close-open inspection in AutoCAD 2024.")
  (princ))
(princ "\nPrepared native authoring recipe; it has not run. Use ATFNATIVEBUILD in a new empty AutoCAD 2024 drawing.")
(princ)
